/* 송쌤과학 음원 변환 스튜디오 · local browser processing only */
(() => {
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PATHS={audio:'M3 10v4m4-8v12m5-15v18m5-14v10m4-7v4',folder:'M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z',chevronDown:'m6 9 6 6 6-6',layers:'m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5',lock:'M6 10h12v11H6V10Zm2 0V6a4 4 0 0 1 8 0v4m-4 4v3',youtube:'M4 5h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Zm6 4 6 3-6 3V9Z',instagram:'M7 3h10a4 4 0 0 1 4 4v10a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V7a4 4 0 0 1 4-4Zm9 9a4 4 0 1 1-8 0 4 4 0 0 1 8 0Zm1-5h.01',undo:'m3 7 5-5M3 7l5 5M3 7h11a7 7 0 0 1 0 14h-3',redo:'m21 7-5-5m5 5-5 5m5-5H10a7 7 0 0 0 0 14h3',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',save:'M4 3h13l4 4v14H3V3h1Zm3 0v6h10V3M7 21v-8h10v8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',help:'M9.1 9a3 3 0 0 1 5.8 1c0 2-3 2-3 4m.1 3h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',moon:'M21 13A9 9 0 1 1 11 3a7 7 0 0 0 10 10Z',sun:'M12 3V1m0 22v-2M3 12H1m22 0h-2M5 5 3 3m18 18-2-2M5 19l-2 2M21 3l-2 2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',repeat:'m17 2 4 4-4 4M3 11V8a2 2 0 0 1 2-2h16M7 22l-4-4 4-4m14-1v3a2 2 0 0 1-2 2H3',scissors:'m8 8 13 13M8 16 21 3M8 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 19a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',sliders:'M4 21v-7m0-6V3m8 18v-9m0-6V3m8 18v-5m0-6V3M1 8h6m2 4h6m2 4h6',bookmark:'M5 3h14v19l-7-5-7 5V3Z',gauge:'M3 18a10 10 0 1 1 18 0H3Zm9-4 5-7',mic:'M8 3h8v12H8V3Zm-3 7v3a7 7 0 0 0 14 0v-3m-7 10v3m-4 0h8',files:'M8 7h13v15H8V7ZM4 17H2V2h13v2',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-4 9 3 3 5-5',plus:'M12 5v14M5 12h14',minus:'M5 12h14',headphones:'M3 14v-3a9 9 0 0 1 18 0v3M3 13h4v8H3v-8Zm14 0h4v8h-4v-8Z',upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5',volumeOff:'M11 5 6 9H2v6h4l5 4V5Zm6 4 5 6m0-6-5 6',volume:'M11 5 6 9H2v6h4l5 4V5Zm4 3a5 5 0 0 1 0 8m3-11a9 9 0 0 1 0 14',split:'M12 3v18M8 8l-5 4 5 4m8-8 5 4-5 4',skip:'M5 4v16m14-16L7 12l12 8V4Z',back:'m11 19-9-7 9-7v14Zm10 0-9-7 9-7v14Z',forward:'m3 5 9 7-9 7V5Zm10 0 9 7-9 7V5Z',play:'m7 3 15 9-15 9V3Z',pause:'M7 3v18m10-18v18',stop:'M5 5h14v14H5V5Z',info:'M12 11v6m0-10h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',close:'m6 6 12 12M6 18 18 6',fit:'M4 9V4h5m6 0h5v5M4 15v5h5m6 0h5v-5M9 12h6',check:'m5 12 4 4L20 5',up:'m6 15 6-6 6 6',down:'m6 9 6 6 6-6',copy:'M8 8h13v13H8V8ZM4 16H2V2h14v2',search:'m21 21-4.3-4.3M17 11a6 6 0 1 1-12 0 6 6 0 0 1 12 0Z',image:'M3 5h18v14H3V5Zm3 12 4-5 3 3 2-2 4 4M9 10h.01',film:'M4 3h16v18H4V3Zm0 5h16M4 12h16M4 16h16M8 3v18m8-18v18',arrow:'M5 12h14m-6-6 6 6-6 6',reverse:'m3 12 5-5m-5 5 5 5M3 12h12a6 6 0 0 1 0 12h-2',grid:'M3 3h8v8H3V3Zm10 0h8v8h-8V3ZM3 13h8v8H3v-8Zm10 0h8v8h-8v-8Z'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${PATHS[name]||PATHS.audio}"/></svg>`}
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}icons();
const M=window.StudioModel;const sources=new Map();let activeSource=null,history=null,tool='convert',version=0,dirty=false,preview=null,result=null,listen='original',selectionPreview=false,zoom=1,scroll=0,silenceRanges=[],capabilities=null;
let output={format:'mp3',bitrate:192,sampleRate:0,channels:0,bitDepth:16,vbr:false,quality:3,compression:5,oggQuality:4,metadataMode:'remove',title:'',artist:'',album:'',videoStyle:'cover',videoSize:'1280x720',videoColor:'#49301f',videoTitle:'',videoSubtitle:''},outputName='수업_음원',targetBytes=null;
// Output formats the engine writes. 'group' decides where a format appears in the panel; bitrates/depths are the choices shown for it.
const FORMAT_INFO={
 mp3:{label:'MP3',desc:'어디서나 재생',group:'lossy',bitrates:[64,96,128,160,192,256,320],defaultBitrate:192},
 m4a:{label:'M4A',desc:'AAC · 애플·유튜브',group:'lossy',bitrates:[64,96,128,160,192,256],defaultBitrate:192},
 aac:{label:'AAC',desc:'ADTS 스트림 · 방송·웹',group:'lossy',bitrates:[64,96,128,160,192,256],defaultBitrate:160},
 m4r:{label:'M4R',desc:'아이폰 벨소리 · 40초 이내',group:'lossy',bitrates:[96,128,160,192],defaultBitrate:128},
 ogg:{label:'OGG',desc:'Vorbis · 열린 형식',group:'lossy',quality:true},
 opus:{label:'Opus',desc:'모노 · 가장 작은 용량 · 말소리',group:'lossy',bitrates:[24,32,48,64,96,128],defaultBitrate:48,monoOnly:true},
 webm:{label:'WebM 오디오',desc:'Opus 모노 · 웹 재생용',group:'lossy',bitrates:[24,32,48,64,96,128],defaultBitrate:48,monoOnly:true},
 wma:{label:'WMA',desc:'윈도우 미디어',group:'lossy',bitrates:[64,96,128,160,192],defaultBitrate:128},
 mp2:{label:'MP2',desc:'방송용 MPEG 레이어 2',group:'lossy',bitrates:[96,128,160,192,256,320],defaultBitrate:192},
 ac3:{label:'AC3',desc:'돌비 디지털 · 최대 5.1',group:'lossy',bitrates:[128,192,256,320,384,448],defaultBitrate:192},
 wav:{label:'WAV',desc:'무압축 · 다시 편집할 때',group:'lossless',depths:[8,16,24,32]},
 flac:{label:'FLAC',desc:'무손실 압축',group:'lossless',depths:[16,24]},
 alac:{label:'ALAC',desc:'애플 무손실 · M4A',group:'lossless',depths:[16,24]},
 aiff:{label:'AIFF',desc:'애플 무압축',group:'lossless',depths:[16,24]},
 caf:{label:'CAF',desc:'애플 코어 오디오',group:'lossless',depths:[16,24]},
 au:{label:'AU',desc:'유닉스 · Sun 오디오',group:'lossless',depths:[16,24]},
 mp4:{label:'MP4 영상',desc:'화면 + 소리 · 유튜브·수업 자료',group:'video',bitrates:[96,128,160,192,256],defaultBitrate:160},
 webmv:{label:'WebM 영상',desc:'VP8 + Vorbis · 웹',group:'video',quality:true}
};
const GROUP_LABELS={lossy:'손실 압축 · 작은 용량',lossless:'무손실 · 무압축',video:'영상 (화면 + 소리)'};
const MAIN_TILES=['mp3','m4a','wav','flac','ogg','mp4'];
const formatLabel=k=>FORMAT_INFO[k]?.label||String(k).toUpperCase();
const isVideo=k=>M.VIDEO_FORMATS.includes(k);
const DEFAULT_ACCEPT='audio/*,video/*,.mkv,.flac,.opus,.m4a,.ogg,.oga,.wma,.aiff,.aif,.caf,.au,.ac3,.mp2,.aac,.webm,.m4r,.amr,.mov,.mp4,.m4v';
const COVER_COLORS=['#49301f','#a34d16','#173e31','#0b1f44','#2a1d55','#1c1c1c','#f7f5f1'];
let coverImage=null,resultUrl=null,menuOpen=true;
// ----- conversion menu: built after a file is opened, from what the file really is (video or audio, which format) -----
const CODEC_FORMAT={mp3:'mp3',aac:'m4a',vorbis:'ogg',opus:'opus',flac:'flac',alac:'alac',wmav1:'wma',wmav2:'wma',ac3:'ac3',mp2:'mp2',pcm_s16le:'wav',pcm_s24le:'wav',pcm_s32le:'wav',pcm_f32le:'wav',pcm_u8:'wav',pcm_s16be:'aiff',pcm_s24be:'aiff'};
const COPYABLE=new Set(['aac','mp3','flac','vorbis','opus','alac','ac3','mp2','wmav2','pcm_s16le','pcm_s24le','pcm_f32le','pcm_u8','pcm_s16be','pcm_s24be']);
const MENU_AUDIO=['wav','m4a','flac','ogg','opus','aac','m4r','alac','aiff','wma','ac3','mp2','caf','au','webm'];
const engine=new AudioEngine(s=>{if(s.message&&processing)$('busyText').textContent=s.message});
let processing=false,jobId=0,busyTimer=null,busyStarted=0,toastTimer=null,restoreFocus=null;
let audioContext=null,playerNode=null,playerGain=null,analyserL=null,analyserR=null,playerBuffer=null,position=0,startedAt=0,playing=false,muted=false,raf=0,playWindow=null,playbackRate=1,compareMatch=false;
let batch=[],batchRunning=false,batchStop=false,recorder=null,recStream=null,recordChunks=[],recordStarted=0,recordElapsed=0,recordTicker=null,recAnalyser=null,recContext=null,recordCancelled=false;
const toolsInfo={convert:['CONVERT AUDIO','음원 변환','소리를 담을 형식과 용량을 선택하세요. 영상으로도 만들 수 있어요.'],edit:['EDIT YOUR SOUND','파형·구간 편집','필요한 소리만 남기고, 자연스럽게 연결하세요.'],effects:['MAKE IT CLEAR','소리 보정','잡음을 줄이고, 듣기 편한 소리로 다듬으세요.'],mix:['TWO TRACK MIX','목소리 + 배경음','설명하는 목소리 뒤에 배경음을 더하세요.'],classroom:['MADE FOR CLASS','수업용 구간 도구','중요한 순간을 표시하고, 반복 음원을 만드세요.'],speed:['TIME & PITCH','속도·음높이·역재생','최종 파일에 저장될 속도·음높이를 바꾸거나 거꾸로 재생하세요.'],record:['RECORD YOUR VOICE','마이크 녹음','설명과 내레이션을 녹음해 바로 편집하세요.'],batch:['BATCH CONVERT','일괄 변환','여러 파일을 차례대로 변환하고 저장하세요.']};
const model=()=>history?.current;
const num=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
function fmt(t){t=Math.max(0,t||0);return `${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}.${Math.floor(t%1*1000).toString().padStart(3,'0')}`}
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const mb=n=>`${(n/1000000).toFixed(n<1000000?3:2)} MB`;
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,error?7000:4300)}
function modal(title,body){if(!$('modal').open)restoreFocus=document.activeElement;$('modalContent').innerHTML=`<div class="modal-head"><h2 id="modalTitle">${esc(title)}</h2><button class="btn icon" data-action="closeModal" aria-label="닫기 (Esc)">${icon('close')}</button></div><div class="modal-body">${body}</div>`;if(!$('modal').open)$('modal').showModal();($('modalContent').querySelector('.modal-body input:not([type=hidden]),.modal-body select,.modal-body textarea')||$('modalContent').querySelector('.modal-head button'))?.focus()}
function returnFocus(){const el=restoreFocus;restoreFocus=null;if(el?.isConnected&&!el.closest('dialog'))el.focus();else if(el)$('workspace').focus()}
function closeModal(){if($('modal').open)$('modal').close();else returnFocus()}
$('modal').addEventListener('close',returnFocus);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});
function getContext(){if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();return audioContext}
async function decode(bytes){const array=bytes instanceof Uint8Array?bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength):bytes.slice(0);return getContext().decodeAudioData(array)}
async function runTask(label,fn){if(processing){toast('진행 중인 작업을 마친 뒤 다시 시도해 주세요.');return null}const id=++jobId;processing=true;busyStarted=Date.now();$('busyText').textContent=label;$('busyTime').textContent='0초 경과';$('busy').hidden=false;busyTimer=setInterval(()=>{$('busyTime').textContent=`${Math.floor((Date.now()-busyStarted)/1000)}초 경과 · 이 기기에서 처리 중`;},500);try{return await fn(()=>{if(id!==jobId)throw Object.assign(new Error('작업을 취소했습니다.'),{code:'CANCELLED'})})}catch(e){if(e.code!=='CANCELLED'){console.warn('[audio-studio]',e.code||'processing-error');toast(e.message||'처리하지 못했습니다. 파일과 설정을 확인해 주세요.',true)}return null}finally{if(id===jobId){processing=false;$('busy').hidden=true;clearInterval(busyTimer)}}}
function cancelTask(){++jobId;engine.cancel();stopPlayback();processing=false;$('busy').hidden=true;clearInterval(busyTimer);toast('작업을 취소했습니다. 다시 시도할 수 있습니다.')}
function setTool(name){if(!toolsInfo[name])return;tool=name;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===name);b.toggleAttribute('aria-current',b.dataset.tool===name);if(b.dataset.tool===name)b.setAttribute('aria-current','page')});$('crumbTool').textContent=toolsInfo[name][1];renderLayout();}
function renderLayout(){const aux=['batch','record'].includes(tool);$('welcome').hidden=!!activeSource||aux;$('workbench').hidden=!activeSource||aux;$('auxPanel').hidden=!aux;$('headerExport').disabled=!activeSource||processing;if(aux){renderAux();return}if(activeSource){renderMenu();renderPanel();renderSource();renderSelection();renderClips();renderResult();drawWave();}}
function sourceProfile(s){const p=s.metadata,ext=((s.originalName||'').match(/\.([a-z0-9]{1,5})$/i)?.[1]||'').toLowerCase();let own=CODEC_FORMAT[p.codec]||null;if(own==='m4a'&&ext==='aac')own='aac';else if(own==='m4a'&&ext==='m4r')own='m4r';else if(['wav','aiff'].includes(own)&&['caf','au'].includes(ext))own=ext;else if(own==='opus'&&ext==='webm')own='webm';const pretty={webm:'WebM',opus:'Opus',mkv:'MKV'}[ext]||(ext?ext.toUpperCase():String(p.codec).toUpperCase());return {video:!!p.video,own:p.video?null:own,label:pretty,codec:p.codec}}
const channelName=n=>n===1?'모노':n===2?'스테레오':`${n}채널`;
function menuGroups(){const s=activeSource;if(!s)return [];const pr=sourceProfile(s),caps=capabilities?.formats||{},ok=f=>caps[f]?.supported!==false,card=(id,title,sub,patch,act)=>({id,title,sub,patch:patch&&{channels:0,...patch},act});const groups=[];
 if(pr.video){const copy=COPYABLE.has(pr.codec)&&s.metadata.tracks?.length&&model()?.clips.length===1&&model().clips[0].sourceId===s.id;
  groups.push({key:'extract',title:'영상에서 소리 꺼내기',desc:'화면은 버리고 소리만 음원 파일로 저장해요.',items:[card('x-mp3','MP3','어디서나 재생 · 192 kbps',{format:'mp3',bitrate:192,vbr:false}),card('x-m4a','M4A','AAC · 아이폰·유튜브 · 192 kbps',{format:'m4a',bitrate:192}),card('x-wav','WAV','무압축 · 다시 편집할 때',{format:'wav',bitDepth:16}),card('x-flac','FLAC','무손실 압축',{format:'flac',bitDepth:16}),card('x-ogg','OGG','Vorbis · 열린 형식',{format:'ogg',oggQuality:4}),card('x-opus','Opus','모노 · 가장 작은 용량 · 말소리',{format:'opus',bitrate:48}),...(copy?[card('x-copy','원본 소리 그대로',`재인코딩 없이 ${pr.codec} 그대로 · 가장 빠름`,null,'copyExtract')]:[])]});
 }else{
  const mp3=pr.own==='mp3'?[card('m-128','MP3 용량 줄이기','128 kbps · 원본 채널',{format:'mp3',bitrate:128,channels:0,vbr:false}),card('m-96','MP3 말소리용','96 kbps · 모노',{format:'mp3',bitrate:96,channels:1,vbr:false}),card('m-64','MP3 가장 작게','64 kbps · 모노',{format:'mp3',bitrate:64,channels:1,vbr:false})]
   :[card('m-192','MP3 일반 공유','192 kbps · 원본 채널',{format:'mp3',bitrate:192,channels:0,vbr:false}),card('m-96','MP3 말소리·수업 녹음','96 kbps · 모노',{format:'mp3',bitrate:96,channels:1,vbr:false}),card('m-320','MP3 음악 고음질','320 kbps · 원본 채널',{format:'mp3',bitrate:320,channels:0,vbr:false})];
  groups.push({key:'mp3',title:pr.own==='mp3'?'MP3 다시 저장':'MP3로',desc:pr.own==='mp3'?'이미 MP3예요. 용량을 줄이거나 말소리용으로 다시 저장할 수 있어요.':'가장 널리 쓰이는 형식이에요. 쓰임에 맞게 고르세요.',items:mp3});
  groups.push({key:'audio',title:'다른 음원 형식으로',desc:`${pr.own?formatLabel(pr.own):pr.label} 말고 다른 형식이 필요할 때 골라요.`,items:MENU_AUDIO.filter(f=>f!==pr.own).map(f=>card('a-'+f,FORMAT_INFO[f].label,FORMAT_INFO[f].desc,{format:f}))});
  groups.push({key:'video',title:'영상 만들기',desc:'소리에 화면을 붙여 유튜브·수업 자료용 영상으로 만들어요.',items:[card('v-still','MP4 정지 화면','1280×720 · 제목 화면 · 빠름',{format:'mp4',videoStyle:'cover',videoSize:'1280x720'}),card('v-waves','MP4 파형 애니메이션','1280×720 · 소리에 맞춰 움직임 · 느림',{format:'mp4',videoStyle:'waves',videoSize:'1280x720'}),card('v-shorts','MP4 세로 쇼츠','1080×1920 · 휴대폰 화면',{format:'mp4',videoStyle:'cover',videoSize:'1080x1920'}),card('v-square','MP4 정사각','1080×1080 · SNS 게시',{format:'mp4',videoStyle:'cover',videoSize:'1080x1080'}),card('v-webm','WebM 영상','1280×720 · VP8 + Vorbis · 웹',{format:'webmv',videoStyle:'cover',videoSize:'1280x720'})]});
 }
 return groups.map(g=>({...g,items:g.items.filter(i=>!i.patch||ok(i.patch.format))})).filter(g=>g.items.length)}
const menuSelected=i=>!!i.patch&&Object.entries(i.patch).every(([k,v])=>output[k]===v);
function outputDetail(o=output){const i=FORMAT_INFO[o.format]||{},parts=[];if(isVideo(o.format))parts.push(o.videoSize.replace('x','×'),o.videoStyle==='waves'?'파형 애니메이션':'정지 화면');else if(i.quality)parts.push(`음질 ${o.oggQuality}`);else if(i.bitrates)parts.push(`${o.bitrate} kbps`);else if(i.depths)parts.push(`${o.bitDepth}비트`);if(i.monoOnly||o.channels===1)parts.push('모노');else if(o.channels===2)parts.push('스테레오');if(o.sampleRate)parts.push(`${o.sampleRate/1000} kHz`);return parts.join(' · ')}
function renderMenu(){const root=$('convertMenu');if(!root)return;const show=!!activeSource&&tool==='convert';root.hidden=!show;if(!show)return;const s=activeSource,p=s.metadata,pr=sourceProfile(s),groups=menuGroups();
 const facts=pr.video?[`영상 파일 · ${pr.label}`,p.video.width&&p.video.height?`${p.video.width}×${p.video.height}`:'',`소리 ${p.codec} · ${channelName(p.channels)}`,fmt(p.duration).slice(0,5)]:[`음원 파일 · ${pr.label}`,p.codec,channelName(p.channels),fmt(p.duration).slice(0,5)];
 const current=`${pr.label} → ${formatLabel(output.format)}${outputDetail()?` · ${outputDetail()}`:''}`;
 root.innerHTML=`<div class="menu-head"><div><span class="eyebrow">PICK A CONVERSION</span><h2 id="menuTitle">${pr.video?'이 영상에서 무엇을 꺼낼까요?':'이 음원을 무엇으로 바꿀까요?'}</h2><div class="menu-facts">${facts.filter(Boolean).map(f=>`<span>${esc(f)}</span>`).join('')}</div></div><button class="btn" data-action="toggleMenu" aria-expanded="${menuOpen}" aria-controls="menuBody">${icon(menuOpen?'up':'down')}${menuOpen?'접기':'다른 변환 고르기'}</button></div>`
 +(menuOpen?`<div id="menuBody">${pr.video?'<p class="menu-note">영상 파일이라 「영상에서 소리 꺼내기」만 보여 드려요. 음원으로 꺼낸 뒤 그 파일을 다시 열면 영상 만들기도 할 수 있어요.</p>':''}${groups.map(g=>`<div class="catalog-group"><h3><span></span>${esc(g.title)}<small>${g.items.length}</small></h3><p class="group-desc">${esc(g.desc)}</p><div class="catalog-grid">${g.items.map(i=>{const on=menuSelected(i);return `<button class="pair-card ${on?'on':''}" data-menu="${i.id}" aria-pressed="${on}"><span><strong>${esc(i.title)}</strong><small>${esc(i.sub)}</small></span>${icon(on?'check':'arrow')}</button>`}).join('')}</div></div>`).join('')}</div>`
 :`<div class="menu-summary">${icon('check')}<span>지금 설정 <strong>${esc(current)}</strong> · 예상 ${mb(M.estimateBytes(model(),output,[...sources.values()]))}</span><button class="btn" data-action="export">${icon('download')}이대로 변환</button></div>`)}
function chooseMenu(id){const item=menuGroups().flatMap(g=>g.items).find(i=>i.id===id);if(!item)return;if(item.act){action(item.act);return}const before=JSON.stringify(output);output={...output,...item.patch};fitOutput(output,false);const changed=JSON.stringify(output)!==before,clamped=item.patch.bitrate!==undefined&&output.bitrate!==item.patch.bitrate;if(changed)invalidate();menuOpen=false;renderLayout();if(changed)persistOutput();const next=$('convertMenu').querySelector('.menu-summary [data-action="export"]')||$('convertMenu').querySelector('[data-action="toggleMenu"]');if(next)next.focus({preventScroll:true});else $('workspace').focus();toast(clamped?`선택했어요 · ${item.title}. 샘플레이트가 ${output.sampleRate/1000} kHz라 ${output.bitrate} kbps까지만 저장돼서 ${output.bitrate} kbps로 맞췄어요. 설정 칸에서 샘플레이트를 바꾸면 더 높일 수 있어요.`:`선택했어요 · ${item.title}${item.sub?` (${item.sub})`:''}. 「이대로 변환」을 누르거나 설정 칸에서 세부 값을 바꾸세요.`);$('convertMenu').scrollIntoView({behavior:'smooth',block:'nearest'})}
// Keep the stored choices valid for the format: bitrate inside its list, bit depth where it exists.
function applyFormat(key,rerender=true){if(!FORMAT_INFO[key])return;output.format=key;fitOutput();invalidate();if(rerender)renderLayout();persistOutput()}
function persistOutput(){try{const {title,artist,album,...rest}=output;localStorage.setItem('ss.audio.output',JSON.stringify({...rest,metadataMode:rest.metadataMode==='edit'?'remove':rest.metadataMode}))}catch{}}
function restoreOutput(){try{const saved=JSON.parse(localStorage.getItem('ss.audio.output')||'null');if(saved&&typeof saved==='object')output=M.validateOutput({...output,...saved,title:'',artist:'',album:''});if(capabilities?.formats?.[output.format]?.supported===false)output.format='mp3';fitOutput(output,false)}catch{output={...output,format:'mp3'}}}
function field(label,key,value,opts={}){const attrs=`data-key="${key}" ${opts.scope?`data-scope="${opts.scope}"`:''}`;let input;if(opts.options)input=`<select ${attrs}>${opts.options.map(([v,l])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${l}</option>`).join('')}</select>`;else input=`<input type="${opts.type||'number'}" ${attrs} value="${esc(value)}" ${opts.min!==undefined?`min="${opts.min}"`:''} ${opts.max!==undefined?`max="${opts.max}"`:''} step="${opts.step||1}">`;return `<label class="field"><span>${label}${opts.type==='range'?`<output>${value}${opts.unit||''}</output>`:''}</span>${input}${opts.help?`<small>${opts.help}</small>`:''}</label>`}
function check(label,key,value,scope='model'){return `<label class="check"><input type="checkbox" data-key="${key}" data-scope="${scope}" ${value?'checked':''}>${label}</label>`}
const actionBtn=(action,label,ico,cls='')=>`<button class="btn ${cls}" data-action="${action}">${ico?icon(ico):''}${label}</button>`;
function renderPanel(){if(!model())return;const d=toolsInfo[tool];$('panelEyebrow').textContent=d[0];$('panelTitle').textContent=d[1];$('panelDescription').textContent=d[2];const m=model();let html='';
if(tool==='convert'){
 const info=FORMAT_INFO[output.format]||{},caps=capabilities?.formats||{},video=isVideo(output.format);
 const tile=v=>{const i=FORMAT_INFO[v],off=caps[v]?.supported===false;return `<button class="format-tile ${output.format===v?'on':''}" data-format="${v}" aria-pressed="${output.format===v}" ${off?`disabled title="${esc(caps[v]?.reason||'현재 엔진에서 지원되지 않는 형식입니다.')}"`:''}><strong>${i.label}</strong><small>${i.desc}</small></button>`};
 html=`<span class="field-title">출력 형식 <strong>${esc(info.label||'')}</strong></span><div class="format-grid">${MAIN_TILES.map(tile).join('')}</div>`;
 html+=`<label class="field format-more"><span>모든 형식 · ${M.OUTPUT_FORMATS.length}가지</span><select data-key="format" data-scope="output" aria-label="출력 형식 전체 목록">${['lossy','lossless','video'].map(g=>`<optgroup label="${GROUP_LABELS[g]}">${M.OUTPUT_FORMATS.filter(k=>FORMAT_INFO[k].group===g).map(k=>`<option value="${k}" ${output.format===k?'selected':''} ${caps[k]?.supported===false?'disabled':''}>${FORMAT_INFO[k].label} · ${FORMAT_INFO[k].desc}</option>`).join('')}</optgroup>`).join('')}</select>${caps[output.format]?.note?`<small>${esc(caps[output.format].note)}</small>`:''}</label>`;
 html+=`<div class="preset-actions"><button class="text-btn" data-action="catalog">${icon('grid')}이 파일에 맞는 변환 메뉴 열기</button></div>`;
 html+=field('빠른 설정','preset','custom',{scope:'special',options:[['custom','직접 설정'],['speech','말소리·수업 녹음 · MP3 96 kbps 모노'],['share','일반 공유 · MP3 192 kbps'],['music','음악 감상용 · MP3 320 kbps'],['small','가장 작은 용량 · Opus 48 kbps 모노'],['edit','추가 편집용 · WAV 16비트'],['youtube','유튜브 올리기 · MP4 영상']]});
 const lowRateMp3=output.format==='mp3'&&output.sampleRate>0&&output.sampleRate<32000;
 if(info.quality)html+=field('음질 단계','oggQuality',output.oggQuality,{scope:'output',options:[[2,'2 · 약 96 kbps'],[4,'4 · 약 128 kbps'],[6,'6 · 약 192 kbps'],[8,'8 · 약 256 kbps']],help:'Vorbis 품질값이에요. 괄호 안 값은 44.1 kHz 스테레오 기준 대략값이고, 실제 용량은 소리에 따라 달라져요.'});
 else if(info.bitrates)html+=field('비트레이트','bitrate',output.bitrate,{scope:'output',options:info.bitrates.filter(v=>!lowRateMp3||v<=160).map(v=>[v,`${v} kbps`]),help:lowRateMp3?'초당 저장하는 소리 정보량 · 22.05 kHz MP3는 160 kbps까지':output.format==='ac3'?'초당 저장하는 소리 정보량 · AC3는 정해진 단계로 맞춰 저장해요':'초당 저장하는 소리 정보량'});
 if(info.depths)html+=field('비트 깊이','bitDepth',output.bitDepth,{scope:'output',options:info.depths.map(d=>[d,d===8?'8비트 · 아주 작은 용량':d===32?'32비트 float · 편집용':`${d}비트`])});
 const rateNote=['opus','webm'].includes(output.format)?'Opus는 48 kHz로 저장돼요':output.format==='ac3'?'AC3는 32·44.1·48 kHz만 가능해요':output.format==='mp2'?'MP2는 16~48 kHz 범위예요':'';
 const channelField=info.monoOnly?`<label class="field"><span>채널</span><select disabled title="${esc(capabilities?.formats?.[output.format]?.note||'Opus는 모노로만 저장해요.')}"><option>모노 (1채널)</option></select><small>Opus는 모노로만 저장해요</small></label>`:field('채널','channels',output.channels,{scope:'output',options:[[0,'원본 유지'],[1,'모노 (1채널)'],[2,'스테레오 (2채널)']]});
 html+=`<div class="fields-2">${field('샘플레이트','sampleRate',output.sampleRate,{scope:'output',options:[[0,'원본 유지'],[16000,'16 kHz'],[22050,'22.05 kHz'],[32000,'32 kHz'],[44100,'44.1 kHz'],[48000,'48 kHz']],help:rateNote})}${channelField}</div>`;
 if(video){
  html+=`<div class="divider"></div><span class="field-title">영상 화면 <strong>${esc(output.videoSize.replace('x','×'))}</strong></span><canvas id="coverPreview" class="cover-preview" aria-label="영상 화면 미리보기"></canvas>`;
  html+=field('화면 모양','videoStyle',output.videoStyle,{scope:'output',options:[['cover','정지 화면 · 빠름 · 작은 용량'],['waves','파형 애니메이션 · 느림 · 큰 용량']],help:output.videoStyle==='waves'?'6 fps로 그려요. 변환에 음원 길이의 약 1/6 시간이 걸리고 분당 약 12 MB가 돼요.':'1초에 1장만 저장해 빠르고 가벼워요. 유튜브·수업 자료에 알맞아요.'});
  html+=field('크기','videoSize',output.videoSize,{scope:'output',options:[['1280x720','1280×720 · 유튜브 기본'],['1920x1080','1920×1080 · 고화질'],['1080x1080','1080×1080 · 정사각'],['1080x1920','1080×1920 · 세로 (쇼츠)']]});
  html+=`<span class="field-title">바탕색</span><div class="swatches" role="group" aria-label="바탕색">${COVER_COLORS.map(c=>`<button class="swatch ${output.videoColor===c?'on':''}" data-color="${c}" style="background:${c}" aria-label="바탕색 ${c}" aria-pressed="${output.videoColor===c}"></button>`).join('')}<label class="swatch custom" title="직접 고르기"><input type="color" data-key="videoColor" data-scope="output" value="${esc(output.videoColor)}" aria-label="바탕색 직접 고르기"></label></div>`;
  html+=field('화면 제목','videoTitle',output.videoTitle,{scope:'output',type:'text',help:'비워 두면 저장할 파일 이름을 써요'})+field('부제목','videoSubtitle',output.videoSubtitle,{scope:'output',type:'text'});
  html+=`<div class="preset-actions">${actionBtn('coverImage',coverImage?'배경 그림 바꾸기':'배경 그림 넣기','image')}${coverImage?actionBtn('coverRemove','그림 제거','trash'):''}</div>${coverImage?`<p class="tiny sub">${esc(coverImage.name)} · 화면에 꽉 차게 넣고 글자가 보이도록 조금 어둡게 해요. 작업 설정 JSON에는 그림이 들어가지 않아요.</p>`:''}`;
 }
 html+=`<details><summary>고급 옵션·용량·태그</summary>`;
 if(output.format==='mp3')html+=check('VBR · 용량이 달라질 수 있어요','vbr',output.vbr,'output')+(output.vbr?field('VBR 품질 (0이 가장 높음)','quality',output.quality,{scope:'output',min:0,max:9}):'');
 if(output.format==='flac')html+=field('압축 수준','compression',output.compression,{scope:'output',type:'range',min:0,max:12,help:'복원되는 음질은 같고, 용량·처리 시간이 달라집니다.'});
 if(output.format==='mp3')html+=`<label class="field"><span>목표 용량 (MB)</span><input id="targetMb" type="number" min=".01" step=".1" value="${targetBytes?targetBytes/1000000:5}"></label>${actionBtn('targetSize','맞는 비트레이트 제안','gauge','block')}`;
 html+=field('태그 처리','metadataMode',output.metadataMode,{scope:'output',options:[['remove','태그 모두 제거'],['keep','첫 번째 원본 태그 유지'],['edit','직접 입력']]});
 if(output.metadataMode==='edit')html+=field('제목','title',output.title,{scope:'output',type:'text'})+field('제작자','artist',output.artist,{scope:'output',type:'text'})+field('앨범','album',output.album,{scope:'output',type:'text'});
 html+='<p class="tiny sub">커버 이미지는 음원 파일에 넣지 않습니다. 파일명과 입력한 태그는 결과에 남을 수 있습니다.</p></details>';
 html+=field('저장할 파일 이름','outputName',outputName,{scope:'special',type:'text'});
 html+=`<div class="output-estimate"><span>예상 용량 · ${fmt(M.duration(m))}</span><strong id="estimate">${mb(M.estimateBytes(m,output,[...sources.values()]))}</strong></div>${actionBtn('export',video?'영상으로 만들고 결과 확인':'변환하고 결과 확인','download','primary block lg')}<div class="hint">${video?'영상의 소리는 현재 편집·보정을 그대로 반영해요. 화면은 위 미리보기처럼 저장돼요.':'비트레이트를 높이거나 WAV로 바꿔도 이미 손실된 소리가 복원되지는 않습니다.'}</div>`;
 if(activeSource.metadata.tracks?.length&&m.clips.length===1&&m.clips[0].sourceId===activeSource.id)html+=`<details><summary>재인코딩 없이 추출</summary><p class="tiny sub">효과·속도·출력 설정을 적용하지 않고 선택한 원본 구간을 복사합니다. 경계에 작은 오차가 있을 수 있습니다.</p>${actionBtn('copyExtract','원본 소리 그대로 추출','download','block')}</details>`;
}else if(tool==='edit'){
 html=`<div class="fields-2">${field('페이드 인 (초)','fadeIn',m.fadeIn,{min:0,max:Math.min(30,M.duration(m)),step:.1})}${field('페이드 아웃 (초)','fadeOut',m.fadeOut,{min:0,max:Math.min(30,M.duration(m)),step:.1})}</div>${field('연결부 크로스페이드 (초)','crossfade',m.crossfade,{min:0,max:10,step:.01,help:'겹치는 시간만큼 최종 음원이 짧아집니다.'})}${check('연결 경계에 5 ms 페이드','edgeFade',m.edgeFade)}${actionBtn('boundaryPreview','연결 부분 확인','headphones','block')}<div class="divider"></div>${field('선택 구간 음량 (dB)','selectionGain',0,{scope:'special',type:'range',min:-30,max:12,unit:' dB'})}${actionBtn('selectionGain','선택 구간에 음량 적용','volume','block')}<div class="divider"></div>${actionBtn('duplicate','선택 구간 복제','copy','block')}<div style="height:8px"></div>${actionBtn('append','다른 파일 이어 붙이기','plus','block')}<div class="hint">시간은 속도·반복 적용 전 편집 구간 기준입니다. 구간 순서는 오른쪽 위·아래 버튼으로 바꿀 수 있습니다.</div><details><summary>편집 이력</summary><div>${history.entries?.map(e=>`<p class="tiny">${esc(typeof e==='string'?e:e.label||'편집')}</p>`).join('')||'<p class="tiny">아직 편집 이력이 없습니다.</p>'}</div></details>${actionBtn('resetEdits','편집 초기화','undo','block')}`;
}else if(tool==='effects'){
 const e=m.effects;html=field('보정 프리셋','effectPreset','custom',{scope:'special',options:[['custom','직접 설정'],['lesson','수업 녹음 정리'],['voice','말소리 선명하게'],['original','음악 원음 유지'],...getPresets().map(p=>[p.id,p.name])]});html+=`<div class="preset-actions">${actionBtn('savePreset','저장','save')}${actionBtn('managePresets','이름 변경·삭제',null)}</div>`;
 html+=field('배경 잡음 감소','noise',e.noise,{scope:'effects',options:[['off','끄기'],['light','약하게'],['medium','보통'],['strong','강하게']]})+check('저음 웅웅거림 줄이기','highpass',e.highpass,'effects')+field('말소리 선명도','clarity',e.clarity,{scope:'effects',type:'range',min:0,max:10});
 html+=field('전체 음량','gainDb',e.gainDb,{scope:'effects',type:'range',min:-30,max:12,unit:' dB'});
 html+=check('음량 균일화 · −16 LUFS 목표','normalize',e.normalize,'effects')+check('갑자기 큰 소리 완화','compressor',e.compressor,'effects')+check('출력 리미터 · 과도한 피크 완화','limiter',e.limiter,'effects');
 html+=field('채널 처리','channelMode',e.channelMode||'keep',{scope:'effects',options:[['keep','원본 그대로'],['left','왼쪽 채널만 (양쪽에 복사)'],['right','오른쪽 채널만 (양쪽에 복사)'],['swap','좌우 바꾸기']],help:'핀 마이크처럼 한쪽에만 녹음된 파일에 쓰세요. 모노 원본에는 영향이 없어요.'});
 html+=`<details><summary>저음·중음·고음 EQ</summary>${field('저음','eqLow',e.eqLow,{scope:'effects',type:'range',min:-12,max:12,unit:' dB'})}${field('중음','eqMid',e.eqMid,{scope:'effects',type:'range',min:-12,max:12,unit:' dB'})}${field('고음','eqHigh',e.eqHigh,{scope:'effects',type:'range',min:-12,max:12,unit:' dB'})}</details><div class="hint">강한 잡음 감소는 목소리나 음악도 바꿀 수 있습니다. 이미 찌그러진 원본을 완전히 복원하지는 못합니다. 균일화는 측정 음량 −50 LUFS 미만의 증폭을 건너뛰고 최대 +18 dB로 제한합니다. 실제 목표 도달 여부는 소리에 따라 달라집니다.</div>${actionBtn('preview','편집본 듣기','headphones','primary block')}${actionBtn('resetEffects','모든 보정 끄기','undo','block')}`;
}else if(tool==='speed'){
 html=field('저장되는 속도','speed',m.speed,{type:'range',min:.5,max:2,step:.05,unit:'×',help:'음높이를 유지하며 길이를 바꿉니다.'})+field('음높이','pitch',m.pitch,{type:'range',min:-12,max:12,step:1,unit:' 반음',help:'속도와 별도로 음높이를 조절합니다.'})+check('거꾸로 재생 · 최종 파일에 저장','reverse',m.reverse)+`<div class="output-estimate"><span>저장될 길이</span><strong>${fmt(M.duration(m))}</strong></div><div class="hint">크게 바꾸면 소리의 자연스러움이 달라질 수 있습니다. 아래 플레이어의 ‘확인용 속도’와 별개의 설정입니다. 거꾸로 재생하면 원본 A와 편집본 B의 시간을 일대일로 맞출 수 없어 처음부터 비교합니다.</div>${actionBtn('preview','변경한 소리 듣기','headphones','primary block')}`;
}else if(tool==='mix'){
 html=`${actionBtn('addBackground',m.mix?'배경음 바꾸기':'배경음 파일 선택','plus','primary block')}`;
 if(m.mix){const x=m.mix,source=sources.get(x.sourceId);html+=`<p class="tiny sub" style="margin-top:10px;overflow-wrap:anywhere">${esc(source?.originalName)}</p><canvas id="mixCanvas" class="mix-wave" aria-label="배경음 파형"></canvas>`;
 html+=field('목소리 음량','voiceGainDb',x.voiceGainDb||0,{scope:'mix',type:'range',min:-36,max:6,unit:' dB'})+field('배경음 음량','gainDb',x.gainDb,{scope:'mix',type:'range',min:-48,max:6,unit:' dB'});
 html+=`<div class="fields-2">${field('목소리 시작 (초)','voiceOffset',x.voiceOffset||0,{scope:'mix',min:0,max:600,step:.1})}${field('배경음 시작 (초)','offset',x.offset,{scope:'mix',min:0,max:600,step:.1})}</div>`;
 html+=check('배경음 반복','loop',x.loop,'mix')+check('목소리 구간에서 배경음 낮추기','duck',x.duck,'mix')+field('믹스 길이','lengthMode',x.lengthMode,{scope:'mix',options:[['voice','목소리 기준'],['longest','가장 긴 트랙 기준']]});
 html+=`<details><summary>구간·페이드·덕킹 세부 조절</summary><div class="fields-2">${field('배경음 시작 구간','start',x.start,{scope:'mix',min:0,max:source.metadata.duration,step:.001})}${field('배경음 끝 구간','end',x.end,{scope:'mix',min:.001,max:source.metadata.duration,step:.001})}${field('페이드 인 (초)','fadeIn',x.fadeIn,{scope:'mix',min:0,max:30,step:.1})}${field('페이드 아웃 (초)','fadeOut',x.fadeOut,{scope:'mix',min:0,max:30,step:.1})}</div>${field('덕킹 감도 (dBFS)','duckThreshold',x.duckThreshold,{scope:'mix',min:-60,max:-6,step:1})}${field('최대 줄일 양 (dB)','duckAmount',x.duckAmount,{scope:'mix',min:0,max:30,step:1})}${field('돌아오는 시간 (초)','duckRelease',x.duckRelease,{scope:'mix',min:.05,max:5,step:.05})}${check('목소리 음소거','voiceMuted',x.voiceMuted,'mix')}${check('배경음 음소거','muted',x.muted,'mix')}${check('배경음만 듣기·저장','solo',x.solo,'mix')}</details><div class="hint">덕킹은 목소리 트랙의 음량을 기준으로 작동합니다. 말소리 인식 기능은 아닙니다. 믹싱 중에는 A/B를 각각 처음부터 비교합니다.</div>${actionBtn('preview','혼합 결과 듣기','headphones','block')}${actionBtn('removeBackground','배경음 제거','trash','block')}`;
 }else html+='<div class="hint">현재 편집 음원을 목소리 트랙으로 사용합니다. 배경음을 선택하면 두 트랙을 한 파일로 저장할 수 있어요.</div>';
}else if(tool==='classroom'){
 html=`<label class="field"><span>북마크 이름</span><input id="bookmarkName" value="도입" maxlength="80"></label>${actionBtn('bookmark','재생 위치에 북마크','bookmark','block')}<div id="bookmarkList">${m.bookmarks.map((b,i)=>`<div class="bookmark-row"><input class="bookmark-name" data-bookmark-name="${i}" value="${esc(b.name)}" maxlength="80" aria-label="${i+1}번 북마크 이름 (바꾸면 바로 저장)"><small>${fmt(b.time)}</small><button class="btn icon" data-bookmark="${i}" aria-label="${esc(b.name)} 위치로 이동">${icon('play')}</button><button class="btn icon" data-remove-bookmark="${i}" aria-label="북마크 삭제">${icon('trash')}</button></div>`).join('')}</div>${actionBtn('exportBookmarks','북마크별 파일 만들기','download','block')}<div class="divider"></div><label class="field"><span>일정 길이로 분할 (초)</span><input type="number" id="splitSeconds" min=".1" max="3600" step=".1" value="30"></label><div class="preset-actions">${actionBtn('splitFixed','구간으로 나누기','split')}${actionBtn('exportClips','구간별 저장','download')}</div><div class="divider"></div>${field('반복 횟수 · 실제 파일에 반영','repeat',m.repeat,{min:1,max:20})}${field('반복 사이 무음 (초)','gap',m.gap,{min:0,max:60,step:.1})}<div class="fields-2">${field('앞 무음 (초)','padStart',m.padStart,{min:0,max:60,step:.1})}${field('뒤 무음 (초)','padEnd',m.padEnd,{min:0,max:60,step:.1})}</div>${actionBtn('repeatSelection','선택 구간으로 반복 파일 구성','repeat','block')}<details><summary>무음 삽입·찾기</summary><label class="field"><span>삽입할 무음 (초)</span><input id="insertSilenceSeconds" type="number" min=".01" max="60" step=".1" value="1"></label>${actionBtn('insertSilence','선택 시작에 무음 삽입','plus','block')}<label class="field"><span>무음 기준 (dBFS)</span><input id="silenceThreshold" type="number" min="-80" max="-10" value="-45"></label><label class="field"><span>최소 무음 (초)</span><input id="silenceMin" type="number" min=".05" max="30" step=".05" value=".5"></label><label class="field"><span>남길 여백 (초)</span><input id="silencePadding" type="number" min="0" max="2" step=".01" value=".1"></label><label class="check"><input id="silenceEdges" type="checkbox" checked>앞뒤 무음만 찾기</label>${actionBtn('detectSilence','제거할 무음 먼저 찾기','gauge','block')}<div id="silenceResults"></div><p class="tiny sub">작은 목소리와 여운이 잘리지 않도록 표시된 구간을 먼저 들어보세요. 적용 후 실행 취소할 수 있습니다.</p></details>`;
}
$('panelBody').innerHTML=html;drawMixWave();drawCoverPreview();}
function renderSource(){if(!activeSource)return;const a=activeSource,p=a.metadata;$('topFile').textContent=a.originalName;$('crumbFile').textContent=a.originalName;$('sourceName').textContent=a.originalName;$('filePill').textContent=mb(a.size);$('sourceMeta').innerHTML=[fmt(p.duration),mb(a.size),p.codec,`${p.sampleRate.toLocaleString()} Hz`,`${p.channels}채널`,p.bitrate?`${Math.round(p.bitrate)} kbps`:'비트레이트 확인할 수 없음',...(p.video?[`영상 ${p.video.codec} ${p.video.width}×${p.video.height}${p.video.fps?` · ${p.video.fps} fps`:''} · 소리만 꺼내요`]:[])].map(x=>`<span>${esc(x)}</span>`).join('');const tracks=p.tracks||[];$('trackPicker').hidden=tracks.length<2;if(tracks.length>1)$('trackPicker').innerHTML=`<label class="field"><span>영상의 오디오 트랙</span><select id="audioTrack">${tracks.map((t,i)=>`<option value="${i}" ${i===a.track?'selected':''}>${i+1}번 · ${esc(t.codec)} ${esc(t.language||'')} ${esc(t.title||'')}</option>`).join('')}</select></label>`;}
function renderSelection(){if(!model())return;const s=model().selection;$('selectionStart').value=s.start.toFixed(3);$('selectionEnd').value=s.end.toFixed(3);$('selectionLength').textContent=fmt(s.end-s.start);$('undoBtn').disabled=!history.canUndo;$('redoBtn').disabled=!history.canRedo;}
function renderClips(){const m=model();if(!m)return;$('clipSummary').textContent=`${m.clips.length}개 구간 · 최종 ${fmt(M.duration(m))}`;$('clipList').innerHTML=m.clips.map((c,i)=>`<div class="clip-row"><span class="clip-index">${String(i+1).padStart(2,'0')}</span><span class="clip-name">${c.sourceId?esc(sources.get(c.sourceId)?.originalName||'음원'):'삽입한 무음'}${c.muted?' · 무음':''}<small>${fmt(c.start)}–${fmt(c.end)} · ${fmt(c.end-c.start)}${c.gain!==1?` · ${Math.round(20*Math.log10(c.gain))} dB`:''}</small></span><button class="btn icon" data-clip-action="up" data-index="${i}" ${i===0?'disabled':''} aria-label="${i+1}번 구간 위로">${icon('up')}</button><button class="btn icon" data-clip-action="down" data-index="${i}" ${i===m.clips.length-1?'disabled':''} aria-label="${i+1}번 구간 아래로">${icon('down')}</button><button class="btn icon" data-clip-action="duplicate" data-index="${i}" aria-label="${i+1}번 구간 복제">${icon('copy')}</button><button class="btn icon" data-clip-action="remove" data-index="${i}" ${m.clips.length===1?'disabled':''} aria-label="${i+1}번 구간 삭제">${icon('trash')}</button></div>`).join('');}
function invalidate(){version++;dirty=true;preview=null;selectionPreview=false;silenceRanges=[];stopPlayback();listen='original';syncListen();if(result)result.stale=true;renderResult();}
// Bookmarks do not change the sound, so they keep the current preview and result valid.
const AUDIO_NEUTRAL=new Set(['bookmark','removeBookmark','renameBookmark']);
function commit(next,label,rerender=true,affectsAudio=true){history.commit(next,label);if(affectsAudio)invalidate();else dirty=true;if(rerender)renderLayout();}
function applyEdit(op,args={},label='구간 편집'){if(!model())return;const had=model().crossfade;try{const next=M.edit(model(),op,args);commit(next,label,true,!AUDIO_NEUTRAL.has(op));if(had&&!next.crossfade)toast('구간을 정확히 편집하기 위해 크로스페이드를 0초로 초기화했습니다.')}catch(e){toast(e.message,true)}}
function updateSelection(start,end){if(!model())return;const d=M.baseDuration(model());if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end>d+.001||end<=start){toast('시작은 끝보다 작고, 구간은 음원 길이 안에 있어야 합니다.',true);renderSelection();return}history.updateSelection(Math.max(0,start),Math.min(d,end));renderSelection();drawWave();}
function sourcePeaks(buffer){const channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),samples=channels[0],step=Math.ceil(samples.length/Math.min(10000,samples.length)),buckets=Math.ceil(samples.length/step),peaks=new Float32Array(buckets);let peak=0,sum=0;for(let ch=0;ch<channels.length;ch++){const data=channels[ch];for(let i=0;i<data.length;i++){const v=Math.abs(data[i]);peak=Math.max(peak,v);sum+=data[i]*data[i];const k=Math.floor(i/step);if(k<buckets)peaks[k]=Math.max(peaks[k],v)}}return {values:peaks,step,duration:buffer.duration,peak,rms:Math.sqrt(sum/(samples.length*channels.length))}}
async function addSource(file,track=0,guard=()=>{},options={}){const a=await engine.analyze(file,track,options);try{guard();let buffer;try{buffer=await decode(a.wav)}catch(e){throw new Error('파형용 소리를 열 수 없습니다. 다른 파일로 시도해 주세요.')}guard();delete a.wav;const s={...a,buffer,peaks:sourcePeaks(buffer),file,track};sources.set(s.id,s);return s}catch(e){engine.removeSource(a.id).catch(()=>{});throw e}}
async function loadFile(file,mode='replace',track=0){if(!file)return;if(!file.size){toast('빈 파일입니다. 소리가 들어 있는 파일을 선택해 주세요.',true);return}if(file.size>120000000){toast('파일당 최대 120 MB입니다. 짧은 구간으로 나눠 주세요.',true);return}stopPlayback();const replacing=mode==='replace'||!activeSource;await runTask('파일 분석 중',async guard=>{
 // Keep the current work until the new file is analysed; a bad or cancelled file must not erase it.
 let s=null,kept=false;try{s=await addSource(file,track,guard,{replacing});if(!capabilities)capabilities=await engine.capabilities();guard();kept=true}finally{if(s&&!kept){sources.delete(s.id);engine.removeSource(s.id).catch(()=>{})}}
 if(replacing){for(const id of [...sources.keys()])if(id!==s.id){sources.delete(id);await engine.removeSource(id).catch(()=>{})}history=null;preview=null;result=null;silenceRanges=[];segmentResults=[];selectionPreview=false;version++;}
 if(mode==='append'&&!replacing){applyEdit('append',{source:s},'파일 이어 붙이기');}else if(mode==='mix'&&activeSource){const m=M.clone(model());m.mix={sourceId:s.id,start:0,end:s.metadata.duration,offset:0,gainDb:-18,loop:true,duck:true,duckThreshold:-30,duckAmount:12,duckRelease:.4,fadeIn:.5,fadeOut:1,muted:false,solo:false,voiceMuted:false,voiceGainDb:0,voiceOffset:0,lengthMode:'voice'};commit(m,'배경음 추가');setTool('mix');}else{activeSource=s;history=new M.History(M.create(s));outputName=file.name.replace(/\.[^.]+$/,'')+'_변환';dirty=false;version++;zoom=1;scroll=0;listen='original';position=0;playerBuffer=s.buffer;if(capabilities?.formats?.[output.format]?.supported===false)output.format='mp3';if(s.metadata.video&&isVideo(output.format)){output.format='mp3';fitOutput(output,false)}menuOpen=true;setTool('convert');}renderLayout();syncListen();});renderLayout();}
function wavePoint(time){if(!model())return 0;for(const t of M.timeline(model())){if(time>=t.start&&time<=t.end){if(t.clip.muted||!t.clip.sourceId)return 0;const s=sources.get(t.clip.sourceId),p=s?.peaks;if(!p)return 0;const at=t.clip.start+time-t.start;return Math.min(1,p.values[Math.min(p.values.length-1,Math.floor(at/p.duration*p.values.length))]*t.clip.gain)}}return 0}
function editablePosition(){const m=model();if(!m)return 0;const t=currentPosition();if(listen==='original'){const hit=M.timeline(m).find(i=>i.clip.sourceId===activeSource.id&&t>=i.clip.start&&t<=i.clip.end);return hit?hit.start+t-hit.clip.start:0}if(selectionPreview)return m.selection.start+t*m.speed;const mapped=M.mapTime(m,t);if(!mapped)return Math.max(0,Math.min(M.baseDuration(m),(t-m.padStart)*m.speed));const item=M.timeline(m)[mapped.clipIndex];return item.start+mapped.time-item.clip.start}
// Move the playhead to a time on the edit timeline, in whichever sound is being listened to.
function seekToEdit(at){const m=model();if(!m)return false;const item=M.timeline(m).find(t=>at>=t.start&&at<=t.end);let ok=true;if(listen==='original'&&item?.clip.sourceId===activeSource.id)position=item.clip.start+at-item.start;else if(listen!=='original'&&!selectionPreview&&!m.mix&&!m.crossfade&&!m.reverse)position=m.padStart+at/m.speed;else ok=false;position=Math.max(0,Math.min(playerBuffer?.duration||0,position));updatePlaybackUI();drawWave();return ok}
function drawWave(){if(!activeSource||!model()||$('workbench').hidden)return;const canvas=$('waveCanvas'),rect=canvas.getBoundingClientRect();if(!rect.width)return;const dpr=devicePixelRatio||1,w=rect.width,h=rect.height;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const css=getComputedStyle(document.documentElement),c=n=>css.getPropertyValue(n).trim();const total=M.baseDuration(model()),shown=total/zoom,start=scroll*(total-shown),x=t=>(t-start)/shown*w;ctx.clearRect(0,0,w,h);ctx.strokeStyle=c('--border-line');ctx.lineWidth=1;ctx.fillStyle=c('--text-mute');ctx.font='10px Pretendard,system-ui';
 // Fewer ticks on narrow screens, and enough decimals that short sounds do not repeat the same label.
 const ticks=Math.max(2,Math.min(8,Math.floor(w/95))),digits=shown<15?8:shown<90?7:5;
 for(let i=0;i<=ticks;i++){const px=i*w/ticks,label=fmt(start+i*shown/ticks).slice(0,digits);ctx.beginPath();ctx.moveTo(px,25);ctx.lineTo(px,h);ctx.stroke();ctx.fillText(label,Math.max(3,Math.min(w-ctx.measureText(label).width-4,px+5)),16)}const sel=model().selection;ctx.fillStyle=c('--wave-selection');ctx.fillRect(x(sel.start),25,x(sel.end)-x(sel.start),h-25);const center=25+(h-25)/2;ctx.strokeStyle=c('--wave');ctx.lineWidth=1.6;ctx.beginPath();for(let px=0;px<w;px+=2.5){const amplitude=Math.max(.008,wavePoint(start+px/w*shown));const a=amplitude*(h-44)/2;ctx.moveTo(px,center-a);ctx.lineTo(px,center+a)}ctx.stroke();for(const r of silenceRanges){ctx.fillStyle=c('--danger-soft');ctx.globalAlpha=.65;ctx.fillRect(x(r.start),25,x(r.end)-x(r.start),h-25);ctx.globalAlpha=1;ctx.strokeStyle=c('--danger');ctx.strokeRect(x(r.start),25,x(r.end)-x(r.start),h-26)}ctx.strokeStyle=c('--accent');ctx.lineWidth=1.5;for(const t of [sel.start,sel.end]){const px=Math.min(w-1,Math.max(1,x(t)));ctx.beginPath();ctx.moveTo(px,25);ctx.lineTo(px,h);ctx.stroke();ctx.fillStyle=c('--accent');ctx.fillRect(px-2,25,4,9)}for(const b of model().bookmarks){const bx=x(b.time);ctx.fillStyle=c('--accent');ctx.fillRect(bx,21,2,11)}const playX=x(editablePosition());if(playX>=0&&playX<=w){ctx.strokeStyle=c('--text-main');ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(playX,25);ctx.lineTo(playX,h);ctx.stroke()}
$('zoomLabel').textContent=zoom===1?'전체':`${zoom}×`;$('waveScroll').hidden=zoom===1;const peak=activeSource.peaks.peak;$('peakLabel').textContent=`원본 샘플 피크 ${peak? (20*Math.log10(peak)).toFixed(1):'−∞'} dBFS${peak>=.999?' · 클리핑 가능성':''}`;$('waveCaption').textContent='편집 구간 파형 · 보정·속도 적용 전 · 드래그로 선택';}
// Zoom around a point (default: the middle of what is on screen) so the view does not jump back to the start.
function setZoom(next,center){const total=M.baseDuration(model()),oldShown=total/zoom;center??=scroll*(total-oldShown)+oldShown/2;zoom=Math.max(1,Math.min(32,next||1));const shown=total/zoom;scroll=zoom===1?0:Math.max(0,Math.min(1,(center-shown/2)/(total-shown)));$('waveScroll').value=scroll;drawWave()}
function drawMixWave(){const canvas=$('mixCanvas'),p=model()?.mix&&sources.get(model().mix.sourceId)?.peaks;if(!canvas||!p)return;requestAnimationFrame(()=>{const w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*2;canvas.height=h*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--wave');ctx.beginPath();for(let x=0;x<w;x+=3){const a=p.values[Math.floor(x/w*p.values.length)]*(h-10)/2;ctx.moveTo(x,h/2-a);ctx.lineTo(x,h/2+a)}ctx.stroke()})}
const rmsCache=new WeakMap();function bufferRms(buffer){if(!rmsCache.has(buffer))rmsCache.set(buffer,sourcePeaks(buffer).rms);return rmsCache.get(buffer)}
function listenerGain(){let gain=muted?0:num($('listenVolume').value,.8);if(compareMatch&&listen!=='original'&&playerBuffer&&activeSource){const a=activeSource.peaks.rms,b=bufferRms(playerBuffer);if(a>.0001&&b>.0001)gain*=Math.min(4,a/b);}return gain;}
function currentPosition(){if(!playing)return position;return Math.min(playerBuffer?.duration||0,position+(getContext().currentTime-startedAt)*playbackRate)}
function stopPlayback(reset=true){if(playing)position=currentPosition();playing=false;if(playerNode){playerNode.onended=null;try{playerNode.stop()}catch{}playerNode.disconnect();playerNode=null}playerGain?.disconnect();playerGain=null;analyserL?.disconnect();analyserR?.disconnect();analyserL=analyserR=null;if(reset)position=0;cancelAnimationFrame(raf);$('playBtn').innerHTML=icon('play');$('playBtn').setAttribute('aria-label','재생 (Space)');$('meterL').value=$('meterR').value=0;updatePlaybackUI();}
function updatePlaybackUI(){const current=currentPosition(),duration=playerBuffer?.duration||0;$('currentTime').textContent=fmt(current);$('totalTime').textContent=fmt(duration);$('seek').max=Math.max(.001,duration);$('seek').value=current;}
function playbackTick(){updatePlaybackUI();drawWave();if(playing&&playWindow&&currentPosition()>=playWindow.end-.002){if($('loop').checked){stopPlayback(false);position=playWindow.start;startPlayback();return}stopPlayback(false);return}if(playing&&analyserL){const l=new Float32Array(analyserL.fftSize),r=new Float32Array(analyserR.fftSize);analyserL.getFloatTimeDomainData(l);analyserR.getFloatTimeDomainData(r);$('meterL').value=Math.min(1,Math.sqrt(l.reduce((a,v)=>a+v*v,0)/l.length)*3);$('meterR').value=Math.min(1,Math.sqrt(r.reduce((a,v)=>a+v*v,0)/r.length)*3)}if(playing)raf=requestAnimationFrame(playbackTick)}
function selectionOutputRange(){if(!model())return null;const s=model().selection,m=model();if(listen==='original'){const items=M.timeline(m).filter(i=>i.end>s.start&&i.start<s.end);if(items.length!==1||items[0].clip.sourceId!==activeSource.id)return null;const i=items[0];return {start:i.clip.start+s.start-i.start,end:i.clip.start+s.end-i.start}}if(selectionPreview)return {start:0,end:playerBuffer.duration};if(m.mix||m.crossfade||m.reverse)return null;return {start:m.padStart+s.start/m.speed,end:m.padStart+s.end/m.speed}}
async function startPlayback(){if(!activeSource||processing)return;if(!playerBuffer){toast('들을 소리를 먼저 준비해 주세요.');return}await getContext().resume();if(playing)return;if(position>=playerBuffer.duration-.005)position=0;playWindow=$('playSelection').checked?selectionOutputRange():null;if($('playSelection').checked&&!playWindow){toast('여러 구간·믹스는 ‘이 구간 미리 듣기’로 확인해 주세요.');$('playSelection').checked=false}if(playWindow&&(position<playWindow.start||position>=playWindow.end))position=playWindow.start;const ctx=getContext();playerNode=ctx.createBufferSource();playerNode.buffer=playerBuffer;playbackRate=num($('listenSpeed').value,1);playerNode.playbackRate.value=playbackRate;playerGain=ctx.createGain();playerGain.gain.value=listenerGain();playerNode.connect(playerGain);playerGain.connect(ctx.destination);const splitter=ctx.createChannelSplitter(2);playerGain.connect(splitter);analyserL=ctx.createAnalyser();analyserR=ctx.createAnalyser();analyserL.fftSize=analyserR.fftSize=256;splitter.connect(analyserL,0);splitter.connect(analyserR,playerBuffer.numberOfChannels>1?1:0);startedAt=ctx.currentTime;playing=true;playerNode.onended=()=>{if(!playing)return;stopPlayback();if($('loop').checked){position=playWindow?.start||0;startPlayback()}};playerNode.start(0,position);$('playBtn').innerHTML=icon('pause');$('playBtn').setAttribute('aria-label','일시정지 (Space)');raf=requestAnimationFrame(playbackTick);}
function syncListen(){document.querySelectorAll('[data-listen]').forEach(b=>{b.classList.toggle('on',b.dataset.listen===listen);b.setAttribute('aria-pressed',String(b.dataset.listen===listen))});$('listenFinal').disabled=!result||result.stale||!result.buffer;if(listen==='original')playerBuffer=activeSource?.buffer||null;else if(listen==='edited')playerBuffer=preview?.buffer||null;else playerBuffer=result?.buffer||null;updatePlaybackUI();}
async function chooseListen(target,autoplay=false){if(!activeSource)return;const wasPlaying=playing,oldPosition=currentPosition(),oldListen=listen;stopPlayback();if(target==='edited'&&(!preview||preview.version!==version||selectionPreview)){await preparePreview(false,false);if(!preview)return}if(target==='final'&&(!result||result.stale)){toast('현재 설정으로 먼저 변환해 주세요.');return}listen=target;selectionPreview=false;syncListen();let mapped=0;if(oldListen==='original'&&target!=='original')mapped=M.reverseMapTime(model(),activeSource.id,oldPosition);else if(oldListen!=='original'&&target==='original'){const p=M.mapTime(model(),oldPosition);mapped=p?.sourceId===activeSource.id?p.time:null}else mapped=oldPosition;if(mapped===null){mapped=0;toast('시간을 일대일로 맞출 수 없는 구간은 처음부터 비교합니다.')}position=Math.min(mapped,playerBuffer?.duration||0);updatePlaybackUI();if(wasPlaying||autoplay)await startPlayback();}
async function preparePreview(selected=false,autoplay=true){if(!activeSource)return;stopPlayback();const ver=version;let target=M.clone(model());if(selected){target=M.edit(target,'trim');target.repeat=1;target.gap=target.padStart=target.padEnd=0;target.mix=null;}const got=await runTask('편집한 소리 준비 중',async guard=>{const data=await engine.render(target,output,{preview:true});guard();const buffer=await decode(data.bytes);guard();if(ver!==version)return null;return {buffer,version:ver,metadata:data.metadata}});if(!got)return;preview=got;listen='edited';selectionPreview=selected;syncListen();position=0;if(selected)toast('선택 구간의 보정·속도를 반영했습니다. 반복·여백·배경음은 제외한 짧은 미리 듣기입니다.');if(autoplay)await startPlayback();}
const downloadUrls=new Set();function download(bytes,mime,name){const blob=bytes instanceof Blob?bytes:new Blob([bytes],{type:mime}),url=URL.createObjectURL(blob);downloadUrls.add(url);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);downloadUrls.delete(url)},60000);toast('다운로드를 요청했습니다. 브라우저의 다운로드 목록을 확인해 주세요.')}
// Store-only ZIP (no compression: audio is already compressed) with UTF-8 names, so Korean file names survive.
const CRC_TABLE=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xEDB88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xFFFFFFFF;for(let i=0;i<bytes.length;i++)c=CRC_TABLE[(c^bytes[i])&255]^(c>>>8);return (c^0xFFFFFFFF)>>>0}
function zipBlob(files){const enc=new TextEncoder(),parts=[],central=[],d=new Date(),time=(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),date=((d.getFullYear()-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate();let offset=0;
 for(const f of files){const name=enc.encode(f.name),crc=crc32(f.bytes),size=f.bytes.length,head=new DataView(new ArrayBuffer(30)),dir=new DataView(new ArrayBuffer(46));
  [[0,0x04034b50,4],[4,20,2],[6,0x0800,2],[10,time,2],[12,date,2],[14,crc,4],[18,size,4],[22,size,4],[26,name.length,2]].forEach(([at,v,len])=>len===4?head.setUint32(at,v,true):head.setUint16(at,v,true));
  [[0,0x02014b50,4],[4,20,2],[6,20,2],[8,0x0800,2],[12,time,2],[14,date,2],[16,crc,4],[20,size,4],[24,size,4],[28,name.length,2],[42,offset,4]].forEach(([at,v,len])=>len===4?dir.setUint32(at,v,true):dir.setUint16(at,v,true));
  parts.push(head,name,f.bytes);central.push(dir,name);offset+=30+name.length+size}
 const size=central.reduce((n,p)=>n+p.byteLength,0),end=new DataView(new ArrayBuffer(22));end.setUint32(0,0x06054b50,true);end.setUint16(8,files.length,true);end.setUint16(10,files.length,true);end.setUint32(12,size,true);end.setUint32(16,offset,true);
 return new Blob([...parts,...central,end],{type:'application/zip'})}
function downloadZip(items,zipName){const used=new Set(),files=items.map(x=>({name:M.safeFilename(x.name,x.extension,used),bytes:x.bytes}));if(files.reduce((n,f)=>n+f.bytes.length,0)>150000000){toast('ZIP으로 묶기에는 결과가 너무 큽니다. 파일을 하나씩 저장해 주세요.',true);return}download(zipBlob(files),'application/zip',M.safeFilename(zipName,'zip'))}
async function decodeResult(data){try{return await decode(data.bytes)}catch{const back=await engine.decodeResult(data.bytes,data.extension);return decode(back.wav)}}
async function exportAudio(copy=false){if(!activeSource)return;stopPlayback();const ver=version;const got=await runTask(copy?'원본 소리 추출 중':'편집·보정·변환 중',async guard=>{let data;if(copy){const m=model();const i=M.timeline(m)[0];if(m.clips.length!==1||i.clip.sourceId!==activeSource.id)throw new Error('재인코딩 없이 추출하려면 원본 파일 한 구간으로 작업해 주세요.');data=await engine.extractCopy(activeSource.id,{start:i.clip.start+m.selection.start,end:i.clip.start+m.selection.end,metadataMode:output.metadataMode})}else{M.validateModel(model(),sources);data=await engine.render(model(),output,await renderOptions())}guard();if(!data.bytes?.length)throw new Error('변환 결과가 비어 있습니다. 다시 시도해 주세요.');let buffer=null,playError='';try{buffer=await decodeResult(data)}catch{playError='이 브라우저에서 결과를 재생할 수 없습니다. 파일을 내려받아 호환되는 플레이어에서 확인해 주세요.'}guard();if(ver!==version)return null;return {...data,buffer,playError,version:ver,name:M.safeFilename(outputName,data.extension),target:!copy&&output.format==='mp3'?targetBytes:null,stale:false,model:M.clone(model()),output:{...output}}});if(got){result=got;if(resultUrl){URL.revokeObjectURL(resultUrl);resultUrl=null}dirty=false;listen='final';selectionPreview=false;syncListen();renderResult();$('resultCard').scrollIntoView({behavior:'smooth',block:'nearest'});toast('변환이 끝났습니다. 최종 파일을 듣거나 다운로드하세요.')}}
function renderResult(){if(!result){$('resultCard').hidden=true;$('listenFinal').disabled=true;if(resultUrl){URL.revokeObjectURL(resultUrl);resultUrl=null}return}$('resultCard').hidden=false;$('listenFinal').disabled=result.stale||!result.buffer;const p=result.metadata,change=(result.bytes.length/activeSource.size-1)*100;let details=typeof result.summary==='string'?result.summary:result.summary?.notes?.join(' · ')||'';const video=result.summary?.kind==='video';if(video&&!result.stale&&!resultUrl)resultUrl=URL.createObjectURL(new Blob([result.bytes],{type:result.mime}));$('resultCard').innerHTML=`<div class="result-heading"><span class="result-check">${icon(result.stale?'info':'check')}</span><div><span class="eyebrow">${result.stale?'SETTINGS CHANGED':'ALL DONE'}</span><h2>${result.stale?'설정이 바뀌었어요':'변환이 완료되었습니다'}</h2></div></div><div class="result-body">${result.stale?'<div class="hint warn">설정이 변경되었습니다. 다시 변환해 주세요. 아래 정보는 이전 결과입니다.</div>':''}<strong>${esc(result.name)}</strong><p>${esc(p.codec)} · ${fmt(p.duration)} · ${mb(result.bytes.length)} · ${p.sampleRate.toLocaleString()} Hz · ${p.channels}채널 · 실제 평균 ${Math.round(result.bytes.length*8/p.duration/1000)} kbps</p><p>${Math.abs(change)<.05?'원본 파일과 크기가 거의 같습니다':`원본 파일 대비 ${Math.abs(change).toFixed(1)}% ${change<0?'작아졌습니다':'커졌습니다'}`}${activeSource.metadata.tracks?.length>1?' · 선택한 오디오 트랙만 포함':''}.</p>${details?`<p>${esc(details)}</p>`:''}<p>${result.summary?.copy?'원본 코덱 그대로 구간을 복사했습니다 · 보정·속도·형식 설정은 적용하지 않았습니다':esc(editSummary(result.model))}</p>${result.target&&result.bytes.length>result.target?`<div class="hint warn">목표 용량 ${mb(result.target)}보다 ${mb(result.bytes.length-result.target)} 큽니다. 비트레이트를 낮추거나 모노로 바꾸거나 구간을 줄여 보세요.</div>`:''}${result.playError?`<div class="hint warn">${esc(result.playError)}</div>`:''}${video&&!result.stale&&resultUrl?`<video class="result-video" controls preload="metadata" src="${resultUrl}" aria-label="만든 영상 미리 보기"></video>`:''}<div class="result-actions"><button class="btn primary" data-action="download" ${result.stale?'disabled':''}>${icon('download')}다운로드</button><button class="btn" data-action="playFinal" ${result.stale||!result.buffer?'disabled':''}>${icon('headphones')}최종 파일 듣기</button>${actionBtn('backSettings','설정으로 돌아가기',null)}${actionBtn('open','새 파일 선택','plus')}</div><div class="next-steps"><span class="sub">이어서 하기</span>${actionBtn('catalog','다른 형식으로','grid')}${video?actionBtn('toMp3','MP3로도 저장','repeat'):actionBtn('toVideo','영상으로 만들기','film')}${result.summary?.format==='m4r'?'':actionBtn('toRingtone','벨소리 M4R','bookmark')}</div></div>`;}
function editSummary(m){const e=m.effects,parts=[`${m.clips.length}개 구간`];
 if(m.speed!==1)parts.push(`속도 ${m.speed}×`);if(m.pitch)parts.push(`음높이 ${m.pitch>0?'+':''}${m.pitch}반음`);if(m.repeat>1)parts.push(`${m.repeat}회 반복`);
 if(m.reverse)parts.push('거꾸로 재생');if(m.fadeIn||m.fadeOut)parts.push('페이드');if(m.crossfade)parts.push(`크로스페이드 ${m.crossfade}초`);if(m.padStart||m.padEnd)parts.push('앞뒤 무음');if(m.mix)parts.push('목소리+배경음 혼합');
 const fx=[e.channelMode&&e.channelMode!=='keep'&&{left:'왼쪽 채널만',right:'오른쪽 채널만',swap:'좌우 바꾸기'}[e.channelMode],e.noise!=='off'&&'잡음 감소',e.highpass&&'저음 웅웅거림 줄이기',e.clarity&&'말소리 선명도',(e.eqLow||e.eqMid||e.eqHigh)&&'EQ',e.gainDb&&`전체 음량 ${e.gainDb>0?'+':''}${e.gainDb} dB`,e.normalize&&'음량 균일화',e.compressor&&'컴프레서',e.limiter&&'리미터'].filter(Boolean);
 return [...parts,...(fx.length?fx:['소리 보정 없음'])].join(' · ')}
function getPresets(){try{const p=JSON.parse(localStorage.getItem('ss.audio.presets')||'[]');return Array.isArray(p)?p.filter(x=>typeof x.name==='string'&&typeof x.id==='string'&&x.effects).slice(0,50):[]}catch{return []}}
function putPresets(p){try{localStorage.setItem('ss.audio.presets',JSON.stringify(p));return true}catch{toast('이 브라우저에서 프리셋을 저장할 수 없습니다.',true);return false}}
function effectPreset(value){const m=M.clone(model());if(value==='original')m.effects={...M.effectsDefault(),limiter:false};else if(value==='lesson')m.effects={...M.effectsDefault(),noise:'light',highpass:true,clarity:2,normalize:true,compressor:true};else if(value==='voice')m.effects={...M.effectsDefault(),noise:'light',highpass:true,clarity:4,eqLow:-2,eqMid:2};else{const p=getPresets().find(p=>p.id===value);if(!p)return;m.effects=p.effects}try{commit(M.validateModel(m,sources),'보정 프리셋 적용')}catch(e){toast(e.message,true)}}
function outputPreset(value){const presets={speech:{format:'mp3',bitrate:96,channels:1,vbr:false},share:{format:'mp3',bitrate:192,channels:0,vbr:false},music:{format:'mp3',bitrate:320,channels:0,vbr:false},small:{format:'opus',bitrate:48,channels:1},edit:{format:'wav',bitDepth:16,sampleRate:0,channels:0},youtube:{format:'mp4',bitrate:160,videoStyle:'cover',videoSize:'1280x720',channels:0}};if(presets[value])output={...output,...presets[value]};fitOutput();invalidate();renderLayout();persistOutput()}
// Keep the stored choices valid for the chosen format: bitrate inside its list, bit depth where it exists.
function fitOutput(o=output,notify=true){const info=FORMAT_INFO[o.format]||{};if(info.bitrates&&!info.bitrates.includes(o.bitrate))o.bitrate=info.defaultBitrate;if(info.depths){if(!info.depths.includes(o.bitDepth))o.bitDepth=16}else if(o.bitDepth===8||o.bitDepth===32)o.bitDepth=16;if(o.format==='mp3'&&o.sampleRate>0&&o.sampleRate<32000&&o.bitrate>160){o.bitrate=160;if(notify)toast('22.05 kHz MP3는 160 kbps까지 저장할 수 있어 비트레이트를 160 kbps로 맞췄어요.')}return o}
// ----- video cover: drawn in the browser (so Korean text uses the site font), then handed to the engine as a PNG -----
const luma=hex=>{const v=hex.replace('#','').match(/.{2}/g).map(x=>parseInt(x,16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2]};
function wrapText(ctx,text,maxWidth,maxLines){const lines=[];let line='';for(const word of text.split(/\s+/).filter(Boolean)){let candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width<=maxWidth){line=candidate;continue}if(line){lines.push(line);line=''}let chunk='';for(const ch of word){if(ctx.measureText(chunk+ch).width>maxWidth&&chunk){lines.push(chunk);chunk=''}chunk+=ch}line=chunk}if(line)lines.push(line);if(lines.length>maxLines){lines.length=maxLines;lines[maxLines-1]=lines[maxLines-1].replace(/.{2}$/,'')+'…'}return lines}
function coverCanvas(){const [w,h]=output.videoSize.split('x').map(Number),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=output.videoColor;ctx.fillRect(0,0,w,h);let ink=luma(output.videoColor)>.5?'#1b1410':'#ffffff';
 if(coverImage?.bitmap){const b=coverImage.bitmap,sc=Math.max(w/b.width,h/b.height),dw=b.width*sc,dh=b.height*sc;ctx.drawImage(b,(w-dw)/2,(h-dh)/2,dw,dh);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,.28)');g.addColorStop(1,'rgba(0,0,0,.66)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ink='#ffffff'}
 const base=Math.min(w,h),pad=Math.round(w*.07);
 if(output.videoStyle==='cover'&&activeSource?.peaks){const p=activeSource.peaks.values,bars=Math.min(160,p.length),bw=(w-pad*2)/bars,top=h*.70,hh=h*.2;ctx.fillStyle=ink;ctx.globalAlpha=.32;for(let i=0;i<bars;i++){const v=p[Math.floor(i/bars*p.length)]||0,bh=Math.max(2,v*hh);ctx.fillRect(pad+i*bw,top+(hh-bh)/2,Math.max(1,bw*.6),bh)}ctx.globalAlpha=1}
 const title=(output.videoTitle||outputName||'').trim(),titleSize=Math.round(base*(w>h?.08:.06)),sub=(output.videoSubtitle||'').trim();
 ctx.fillStyle=ink;ctx.textBaseline='alphabetic';ctx.font=`700 ${titleSize}px Pretendard, 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif`;const lines=title?wrapText(ctx,title,w-pad*2,3):[];let y=Math.round(h*(output.videoStyle==='cover'?.30:.22))+titleSize;
 for(const line of lines){ctx.fillText(line,pad,y);y+=Math.round(titleSize*1.25)}
 if(sub){ctx.globalAlpha=.8;ctx.font=`500 ${Math.round(base*.036)}px Pretendard, 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif`;y+=Math.round(base*.02);for(const line of wrapText(ctx,sub,w-pad*2,2)){ctx.fillText(line,pad,y);y+=Math.round(base*.05)}ctx.globalAlpha=1}
 ctx.globalAlpha=.7;ctx.font=`500 ${Math.round(base*.028)}px Pretendard, sans-serif`;ctx.fillText(model()?fmt(M.duration(model())).slice(0,5):'',pad,h-Math.round(h*.06));ctx.globalAlpha=1;return c}
function drawCoverPreview(){const el=$('coverPreview');if(!el||!isVideo(output.format))return;const [w,h]=output.videoSize.split('x').map(Number);const width=el.clientWidth||260,height=Math.round(width*h/w);el.style.aspectRatio=`${w}/${h}`;el.width=width*2;el.height=height*2;const ctx=el.getContext('2d');ctx.drawImage(coverCanvas(),0,0,el.width,el.height)}
async function renderOptions(){if(!isVideo(output.format))return {};const blob=await new Promise(r=>coverCanvas().toBlob(r,'image/png'));if(!blob)throw new Error('영상 화면 그림을 만들지 못했습니다. 다른 크기로 다시 시도해 주세요.');return {cover:new Uint8Array(await blob.arrayBuffer()),waveColor:luma(output.videoColor)>.5&&!coverImage?'#1b1410':'#ffffff'}}
async function chooseCover(file){if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>20000000){toast('PNG·JPG·WebP 그림을 20 MB 이내로 선택해 주세요.',true);return}try{const bitmap=await createImageBitmap(file);coverImage?.bitmap?.close?.();coverImage={name:file.name,bitmap};invalidate();renderLayout()}catch{toast('이 그림을 열 수 없습니다. 다른 파일로 시도해 주세요.',true)}}
function help(privacy=false){modal(privacy?'내 파일은 어디에서 처리되나요?':'음원 스튜디오 사용 안내',`<div class="hint"><strong>영상과 음원은 서버에 전송되거나 저장되지 않습니다.</strong><br>선택한 파일의 변환·추출·편집은 사용 중인 기기의 브라우저 안에서 처리됩니다. 완성된 파일은 다운로드 버튼을 눌러 내 기기에 저장할 수 있습니다.</div><h3>이 순서로 사용해 보세요</h3><p>파일 선택 → 구간 편집 → 형식·용량 선택 → 전후 듣기 → 변환 → 최종 듣기 → 다운로드</p><p><b>원본 A</b>는 처음 소리, <b>편집본 B</b>는 편집·보정을 반영한 소리, <b>최종 파일</b>은 실제 인코딩된 다운로드 파일입니다. 설정을 바꾸면 다시 변환하세요.</p><h3>키보드로 편하게</h3><table><tr><td><kbd>Space</kbd></td><td>재생·일시정지 (작업 화면에서)</td></tr><tr><td><kbd>←</kbd> <kbd>→</kbd></td><td>5초 이동</td></tr><tr><td><kbd>Ctrl/Cmd + Z</kbd></td><td>실행 취소</td></tr><tr><td><kbd>Ctrl/Cmd + Shift + Z</kbd></td><td>다시 실행</td></tr><tr><td><kbd>1</kbd>–<kbd>8</kbd></td><td>편집 도구 선택</td></tr><tr><td><kbd>Esc</kbd></td><td>도움말 닫기</td></tr></table><h3>실행과 저장</h3><p>처음 접속할 때 프로그램·글꼴을 내려받습니다. 음원·파일명·태그는 전송하지 않습니다. 원본과 결과를 브라우저 저장소에 자동 보관하지 않으므로 창을 닫기 전에 다운로드하세요. 작업 설정 JSON에는 원본 파일명 등이 포함되지만 소리 자체는 없습니다.</p><p>파일당 120 MB, 원본 합계 200 MB, 한 번의 디코딩·출력 PCM 256 MB 이내입니다. 기기에 따라 더 작은 파일도 처리가 어려울 수 있습니다. 최신 PC Chrome·Edge를 권장하며 다른 환경은 검증 문서를 확인하세요.</p><h3>저장할 수 있는 형식</h3><p>손실 압축 MP3 · M4A(AAC) · AAC · M4R(벨소리) · OGG(Vorbis) · Opus · WebM(Opus) · WMA · MP2 · AC3, 무손실·무압축 WAV(8·16·24·32비트) · FLAC · ALAC · AIFF · CAF · AU, 영상 MP4(H.264 + AAC) · WebM(VP8 + Vorbis)입니다. Opus·WebM 오디오는 이 엔진에서 스테레오 인코딩이 소리에 따라 멈추는 문제가 있어 모노로만 저장합니다. 영상은 바탕색·제목·배경 그림으로 만든 정지 화면(1 fps) 또는 파형 애니메이션(6 fps)입니다. LUFS·true peak 분석 수치는 기본 화면에서 제공하지 않으며 파형 피크는 샘플 피크입니다.</p><div class="actions">${actionBtn('offline','오프라인 사용 준비','download')}${actionBtn('clearCache','앱 자원 캐시 지우기','trash')}${actionBtn('closeModal','닫기',null,'primary')}</div>`)}
function projectDialog(){modal('작업 설정 저장·불러오기','<p>이 파일은 편집 설정만 담고 있습니다. 다시 열 때 원본 음원이 필요합니다.</p><p>설정 파일에는 원본 파일명·크기·길이·선택한 오디오 트랙과 편집·효과·북마크·출력 설정이 포함됩니다. 음원 바이트와 변환 결과는 포함하지 않습니다.</p><div class="hint">먼저 필요한 원본을 열고, 추가 원본은 이어 붙이기 또는 배경음으로 불러온 다음 설정을 가져오세요. 원본 정보가 다르면 자동 연결하지 않습니다.</div><div class="actions">'+actionBtn('loadProject','설정 가져오기','folder')+`<button class="btn primary" data-action="saveProject" ${!activeSource?'disabled':''}>${icon('save')}설정 파일 저장</button></div>`)}
async function importProject(file){if(!file)return;if(!activeSource){toast('먼저 설정에 사용한 원본 음원을 선택해 주세요.',true);return}if(file.size>1048576){toast('설정 파일은 1 MB 이하만 열 수 있습니다.',true);return}try{const p=M.importProject(await file.text(),sources);output={...output,...p.output};if(capabilities?.formats?.[output.format]?.supported===false)output.format='mp3';fitOutput(output,false);persistOutput();commit(p.model,'작업 설정 불러오기');closeModal();toast('원본을 확인하고 편집 설정을 불러왔습니다.')}catch(e){toast(e.message,true)}}
async function offline(clear=false){if(!('serviceWorker'in navigator)||!isSecureContext){toast('HTTPS 또는 localhost에서 오프라인 준비를 사용할 수 있습니다.',true);return}await runTask(clear?'앱 자원 캐시 지우는 중':'오프라인 실행 자원 준비 중',async guard=>{if(clear){for(const key of await caches.keys())if(key.startsWith('songsam-audio-static-'))await caches.delete(key);const reg=await navigator.serviceWorker.getRegistration('./');if(reg)await reg.unregister();guard();toast('앱 자원 캐시를 지웠습니다. 현재 음원 작업은 그대로입니다.');return}const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;guard();const worker=reg.active;if(!worker)throw new Error('오프라인 준비가 아직 끝나지 않았습니다. 다음 접속 후 다시 확인해 주세요.');const status=await new Promise((resolve,reject)=>{const ch=new MessageChannel();const timeout=setTimeout(()=>reject(new Error('캐시 확인 시간이 초과되었습니다.')),15000);ch.port1.onmessage=e=>{clearTimeout(timeout);resolve(e.data)};worker.postMessage({type:'CACHE_STATUS'},[ch.port2])});guard();if(status.ready)toast('오프라인 사용 준비 완료. 브라우저가 캐시를 삭제하면 다시 준비해야 합니다.');else throw new Error('일부 자원이 준비되지 않았습니다. 연결을 확인하고 다시 시도해 주세요.');})}
function renderAux(){const root=$('auxPanel');if(tool==='record'){root.innerHTML=`<span class="eyebrow">RECORD YOUR VOICE</span><h2>수업의 목소리를 담아 보세요.</h2><p>녹음 시작을 눌렀을 때만 마이크 권한을 요청합니다. 녹음을 마치면 바로 파형을 편집할 수 있어요.</p><label class="field" style="max-width:400px"><span>입력 장치</span><select id="recordDevice" ${recorder?'disabled':''}><option value="">기본 마이크</option></select><small>마이크를 허용한 뒤 연결된 장치 이름을 볼 수 있습니다.</small></label><div class="record-time" id="recordTime">${fmt(recordElapsed/1000)}</div><p id="recordState">${recorder?(recorder.state==='paused'?'녹음 일시정지':'녹음 중 · 소리는 내 기기에만 머물러요'):'녹음을 시작할 준비가 되었어요'}</p><label class="field" style="max-width:400px"><span>입력 음량</span><meter id="recordMeter" min="0" max="1" value="0" style="width:100%;height:15px"></meter></label><div class="actions">${!recorder?actionBtn('recordStart','녹음 시작','mic','primary'):actionBtn('recordStop','녹음 마치고 편집','stop','primary')}${recorder?`<button class="btn" data-action="recordPause" ${typeof recorder.pause!=='function'?'disabled title="이 브라우저는 녹음 일시정지를 지원하지 않습니다."':''}>${icon('pause')}${recorder.state==='paused'?'녹음 재개':'일시정지'}</button>${actionBtn('recordCancel','녹음 취소','trash')}`:''}${actionBtn('open','파일에서 시작','folder')}</div><div class="hint">녹음은 HTTPS 또는 localhost에서 지원됩니다. 사용이 어렵다면 기기의 녹음 앱에서 저장한 파일을 선택하세요. 녹음을 마치거나 취소하면 마이크를 해제합니다.</div>`;if(navigator.mediaDevices?.enumerateDevices)navigator.mediaDevices.enumerateDevices().then(devices=>{const select=$('recordDevice');if(!select)return;devices.filter(d=>d.kind==='audioinput'&&d.deviceId).forEach((d,i)=>{const option=document.createElement('option');option.value=d.deviceId;option.textContent=d.label||`마이크 ${i+1}`;select.append(option)})}).catch(()=>{});
}else{root.innerHTML=`<div class="section-row"><div><span class="eyebrow">BATCH CONVERT</span><h2>여러 음원을 차례대로.</h2></div>${actionBtn('batchAdd','파일 추가','plus')}</div><p>각 파일을 순서대로 변환합니다. 개별 파일의 형식·프리셋과 이름을 고른 뒤 시작하세요. 영상 만들기는 파일을 하나씩 열어 진행해요.</p><div class="hint">일괄 변환은 각 원본 전체를 변환합니다. 현재 작업의 구간 편집·믹스 설정은 적용하지 않습니다. 결과는 하나씩 저장하거나, 두 개 이상이면 ZIP 파일 하나로 묶어 저장할 수 있어요.</div><div id="batchList">${batch.length?batch.map((b,i)=>`<div class="batch-row ${b.state||''}"><span class="clip-index">${i+1}</span><div class="batch-info"><strong>${esc(b.file.name)}</strong><small>${mb(b.file.size)} · ${esc(b.message||'대기 중')}</small></div><select data-batch-format="${i}" aria-label="${i+1}번 출력 형식" style="width:96px" ${batchRunning?'disabled':''}>${M.OUTPUT_FORMATS.filter(f=>!isVideo(f)).map(f=>`<option value="${f}" ${b.output.format===f?'selected':''} ${capabilities?.formats?.[f]?.supported===false?'disabled':''}>${formatLabel(f)}</option>`).join('')}</select><select data-batch-preset="${i}" aria-label="${i+1}번 출력 프리셋" style="width:105px" ${batchRunning?'disabled':''}><option value="share" ${b.preset==='share'?'selected':''}>일반 공유</option><option value="speech" ${b.preset==='speech'?'selected':''}>말소리</option><option value="music" ${b.preset==='music'?'selected':''}>음악</option></select><input data-batch-name="${i}" value="${esc(b.name)}" aria-label="${i+1}번 출력 이름" ${batchRunning?'disabled':''}>${b.result?`<button class="btn" data-batch-download="${i}" aria-label="${i+1}번 결과 저장">${icon('download')}저장</button>`:`<button class="btn icon" data-batch-up="${i}" ${i===0||batchRunning?'disabled':''} aria-label="${i+1}번 파일 위로">${icon('up')}</button><button class="btn icon" data-batch-remove="${i}" ${batchRunning?'disabled':''} aria-label="${i+1}번 파일 제거">${icon('trash')}</button>`}</div>`).join(''):'<div class="hint">아직 파일이 없습니다. 파일 추가로 변환 목록을 만들어 주세요.</div>'}</div><div class="actions"><button class="btn primary" data-action="batchStart" ${!batch.length||batchRunning?'disabled':''}>${icon('repeat')}대기·실패 항목 변환</button>${batch.filter(b=>b.result).length>1?`<button class="btn" data-action="batchZip" ${batchRunning?'disabled':''}>${icon('download')}완료한 파일 ZIP으로 저장</button>`:''}${actionBtn('batchClear','목록 비우기','trash')}</div><p class="tiny sub">작업 취소는 처리 중인 항목을 중단하고 다음 항목으로 이어집니다. 변환을 마친 결과는 이 화면에서 다시 다운로드할 수 있습니다.</p>`;}}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('이 환경은 녹음을 지원하지 않습니다. 녹음한 파일을 선택해 주세요.',true);return}if(recorder)return;try{const device=$('recordDevice')?.value;recStream=await navigator.mediaDevices.getUserMedia({audio:device?{deviceId:{exact:device}}:true});const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(recStream,mime?{mimeType:mime}:{});recordChunks=[];recordCancelled=false;recordElapsed=0;recordStarted=Date.now();const rec=recorder;rec.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};rec.onerror=()=>{recordCancelled=true;stopRecording(true);toast('녹음을 계속할 수 없습니다. 파일 선택으로 시작해 주세요.',true)};rec.onstop=async()=>{const cancelled=recordCancelled;const mime=rec.mimeType||'audio/webm',blob=new Blob(recordChunks,{type:mime});recordChunks=[];releaseMic();recorder=null;if(tool==='record')renderAux();if(!cancelled&&blob.size){const ext=mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm';await loadFile(new File([blob],`수업_녹음_${localDate()}.${ext}`,{type:mime}));}else if(!cancelled)toast('녹음된 소리가 없습니다. 다시 녹음해 주세요.',true)};rec.start(250);recContext=new (window.AudioContext||window.webkitAudioContext)();recAnalyser=recContext.createAnalyser();recAnalyser.fftSize=256;recContext.createMediaStreamSource(recStream).connect(recAnalyser);recordTicker=setInterval(()=>{if(recorder?.state==='recording')recordElapsed=Date.now()-recordStarted;if($('recordTime'))$('recordTime').textContent=fmt(recordElapsed/1000);if(recAnalyser&&$('recordMeter')){const data=new Float32Array(256);recAnalyser.getFloatTimeDomainData(data);$('recordMeter').value=Math.min(1,Math.sqrt(data.reduce((s,v)=>s+v*v,0)/data.length)*4)}if(recordChunks.reduce((s,b)=>s+b.size,0)>100000000)stopRecording(false)},150);renderAux();}catch(e){releaseMic();recorder=null;toast('마이크를 사용할 수 없습니다. 권한·연결을 확인하거나 파일을 선택해 주세요.',true)}}
function releaseMic(){recStream?.getTracks().forEach(t=>t.stop());recStream=null;recContext?.close().catch(()=>{});recContext=null;recAnalyser=null;clearInterval(recordTicker)}
function stopRecording(cancel=false){recordCancelled=cancel;if(recorder&&recorder.state!=='inactive')recorder.stop();releaseMic()}
function addBatch(files){for(const file of files){if(!file.size||file.size>120000000){toast(`${file.name}: 빈 파일이거나 120 MB를 넘습니다.`,true);continue}if(batch.length>=30){toast('한 번에 최대 30개 파일을 추가할 수 있습니다.',true);break}batch.push({file,name:file.name.replace(/\.[^.]+$/,'')+'_변환',output:fitOutput({...output,format:isVideo(output.format)?'mp3':output.format},false),preset:'share',state:'waiting',result:null})}setTool('batch')}
async function runBatch(){if(batchRunning||processing)return;batchRunning=true;batchStop=false;stopPlayback();for(const b of batch){if(batchStop)break;if(b.result)continue;let tempId=null,reason='';b.state='running';b.message='변환 중';renderAux();const got=await runTask(`일괄 변환 중 · ${batch.indexOf(b)+1}/${batch.length}`,async guard=>{try{const s=await engine.analyze(b.file);tempId=s.id;delete s.wav;guard();const m=M.create(s);const data=await engine.render(m,b.output);guard();if(!data.bytes?.length)throw new Error('비어 있는 결과입니다. 다시 시도해 주세요.');return data}catch(e){reason=e.code==='CANCELLED'?'취소함':e.message||'처리하지 못함';throw e}});if(got){b.result=got;b.state='done';b.message=`완료 · ${mb(got.bytes.length)} · ${got.metadata.codec}`}else{b.state='failed';b.message=`${reason||'취소함'} · 다시 시작하면 재시도합니다`}if(tempId)await engine.removeSource(tempId).catch(()=>{});renderAux();const total=batch.reduce((n,x)=>n+(x.result?.bytes.length||0),0);if(total>100000000){toast('결과 합계가 100 MB를 넘었습니다. 결과를 저장하고 목록을 비운 뒤 나머지를 처리해 주세요.',true);break}}batchRunning=false;renderAux();}
let segmentResults=[];
async function exportSegments(bookmarks=false){if(!model())return;const ranges=bookmarks?M.bookmarkSegments(model()):M.timeline(model()).map((c,i)=>({start:c.start,end:c.end,name:`구간${i+1}`}));if(ranges.length>100){toast('구간별 파일은 한 번에 100개까지 만들 수 있습니다.',true);return}segmentResults=[];const segmentOptions=await renderOptions();await runTask('구간별 파일 만드는 중',async guard=>{const used=new Set();for(let i=0;i<ranges.length;i++){const r=ranges[i];let m=M.edit(model(),'trim',r);m.repeat=1;m.gap=m.padStart=m.padEnd=0;m.mix=null;const data=await engine.render(m,output,segmentOptions);guard();segmentResults.push({...data,name:M.safeFilename(`${outputName}_${String(i+1).padStart(2,'0')}_${r.name}`,data.extension,used)});if(segmentResults.reduce((n,x)=>n+x.bytes.length,0)>100000000)throw new Error('구간 결과가 100 MB를 넘었습니다. 만들어진 파일을 저장하고 구간을 줄여 주세요.')}});if(segmentResults.length)modal('구간별 음원 파일',`<p>각 구간에 현재 보정·속도를 적용했습니다. 반복·여백·배경음은 제외했습니다.</p>${segmentResults.map((r,i)=>`<div class="batch-row"><span class="batch-info"><strong>${esc(r.name)}</strong><small>${mb(r.bytes.length)} · ${fmt(r.metadata.duration)}</small></span><button class="btn" data-segment-download="${i}">${icon('download')}다운로드</button></div>`).join('')}<div class="actions">${actionBtn('closeModal','닫기',null)}${segmentResults.length>1?actionBtn('segmentZip',`${segmentResults.length}개 모두 ZIP으로 저장`,'download','primary'):''}</div>`)}
async function findSilence(){if(!model())return;const opts={thresholdDb:num($('silenceThreshold').value,-45),minDuration:num($('silenceMin').value,.5),padding:num($('silencePadding').value,.1),edgesOnly:$('silenceEdges').checked};const m=M.clone(model());Object.assign(m,{crossfade:0,speed:1,pitch:0,repeat:1,gap:0,padStart:0,padEnd:0,fadeIn:0,fadeOut:0,mix:null});m.effects={...M.effectsDefault(),limiter:false};const got=await runTask('실제 소리에서 무음 찾는 중',async guard=>{const d=await engine.render(m,{...output,format:'wav',sampleRate:22050,channels:1},{preview:true});guard();const buffer=await decode(d.bytes);guard();return M.detectSilence(buffer,opts)});if(!got)return;silenceRanges=got;drawWave();$('silenceResults').innerHTML=`<div class="hint">${got.length?`${got.length}개 구간 · 합계 ${fmt(got.reduce((n,r)=>n+r.duration,0))}`:'설정한 기준에서 제거할 무음을 찾지 못했습니다.'}</div>${got.map((r,i)=>`<div class="bookmark-row"><span>${fmt(r.start)}–${fmt(r.end)}</span><button class="btn" data-silence-listen="${i}">듣기</button></div>`).join('')}${got.length?actionBtn('applySilence','표시된 무음 제거','scissors','block'):''}`;}
function clearWork(){stopRecording(true);stopPlayback();engine.dispose();sources.clear();activeSource=null;history=null;preview=null;result=null;playerBuffer=null;batch=[];segmentResults=[];silenceRanges=[];dirty=false;version++;menuOpen=true;coverImage?.bitmap?.close?.();coverImage=null;if(resultUrl){URL.revokeObjectURL(resultUrl);resultUrl=null}for(const url of downloadUrls)URL.revokeObjectURL(url);downloadUrls.clear();$('topFile').textContent='파일을 선택해 주세요';$('crumbFile').textContent='나의 음원 작업실';$('filePill').textContent='파일 선택 대기';$('undoBtn').disabled=$('redoBtn').disabled=true;setTool('convert');closeModal();toast('현재 작업 데이터를 지웠습니다. 다운로드한 파일은 삭제하지 않습니다.')}
function saveProject(){if(!model())return;try{const json=M.exportProject(model(),output,sources);download(json,'application/json',M.safeFilename(outputName+'_작업설정','json'));dirty=false;closeModal()}catch(e){toast(e.message,true)}}
async function action(name){switch(name){
case 'open':if(processing)return;if(recorder)stopRecording(true);$('fileInput').click();break;
case 'catalog':{if(!activeSource){$('fileInput').click();break}menuOpen=true;if(tool!=='convert')setTool('convert');else renderMenu();const m=$('convertMenu');(m.querySelector('.pair-card.on')||m.querySelector('.pair-card')||m.querySelector('[data-action="toggleMenu"]'))?.focus({preventScroll:true});m.scrollIntoView({behavior:'smooth',block:'start'});break}
case 'toggleMenu':menuOpen=!menuOpen;renderMenu();$('convertMenu').querySelector('[data-action="toggleMenu"]')?.focus();break;
case 'toMp3':applyFormat('mp3');toast('출력 형식을 MP3로 바꿨어요. 변환을 다시 눌러 주세요.');break;
case 'toVideo':applyFormat('mp4');toast('MP4 영상 설정으로 바꿨어요. 화면 제목·바탕색을 정한 뒤 변환하세요.');break;
case 'toRingtone':applyFormat('m4r');toast('M4R 벨소리 설정으로 바꿨어요. 40초 이내 구간을 남기고 변환하세요.');break;
case 'coverImage':$('coverInput').click();break;
case 'coverRemove':coverImage?.bitmap?.close?.();coverImage=null;invalidate();renderLayout();break;
case 'append':if(activeSource)$('appendInput').click();else $('fileInput').click();break;
case 'home':setTool('convert');break;
case 'batch':case 'record':setTool(name);break;
case 'theme':document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('ss.theme',document.documentElement.dataset.theme)}catch{}syncThemeButton();drawWave();drawMixWave();drawCoverPreview();break;
case 'help':case 'privacy':help(name==='privacy');break;
case 'project':projectDialog();break;
case 'closeModal':closeModal();break;
case 'cancel':cancelTask();break;
case 'clear':modal('작업 데이터를 지울까요?','<p>현재 불러온 원본, 편집, 녹음과 변환 결과를 닫습니다. 이미 다운로드한 파일은 삭제하지 않습니다.</p><div class="actions">'+actionBtn('closeModal','돌아가기',null)+actionBtn('clearConfirm','작업 데이터 지우기','trash','danger')+'</div>');break;
case 'clearConfirm':clearWork();break;
case 'undo':if(history?.canUndo){history.undo();invalidate();renderLayout()}break;
case 'redo':if(history?.canRedo){history.redo();invalidate();renderLayout()}break;
case 'trim':case 'delete':case 'silence':case 'duplicate':applyEdit(name,{}, {'trim':'선택 구간 남기기',delete:'선택 구간 삭제',silence:'선택 구간 무음',duplicate:'선택 구간 복제'}[name]);break;
case 'split':applyEdit('split',{time:editablePosition()},'재생 위치에서 분할');break;
case 'selectAll':if(model())updateSelection(0,M.baseDuration(model()));break;
case 'zoomIn':case 'zoomOut':if(model())setZoom(name==='zoomIn'?zoom*2:zoom/2);break;
case 'zoomReset':setZoom(1);break;
case 'zoomSelection':{if(!model())break;const s=model().selection,len=s.end-s.start;setZoom(2**Math.floor(Math.log2(M.baseDuration(model())/(len*1.15))),(s.start+s.end)/2);break}
case 'play':if(playing)stopPlayback(false);else await startPlayback();break;
case 'stop':stopPlayback();break;
case 'start':case 'back':case 'forward':{const was=playing,t=currentPosition();stopPlayback(false);position=Math.max(0,Math.min(playerBuffer?.duration||0,name==='start'?0:t+(name==='back'?-5:5)));updatePlaybackUI();drawWave();if(was)startPlayback();break}
case 'mute':muted=!muted;$('muteBtn').innerHTML=icon(muted?'volumeOff':'volume');if(playerGain)playerGain.gain.value=listenerGain();break;
case 'preview':await preparePreview();break;
case 'previewSelection':await preparePreview(true);break;
case 'boundaryPreview':{const timeline=M.timeline(model());if(timeline.length<2){toast('구간이 두 개 이상일 때 연결 부분을 들어볼 수 있습니다.');break}const at=timeline[1].start;updateSelection(Math.max(0,at-1.5),Math.min(M.baseDuration(model()),at+1.5));await preparePreview(true);break}
case 'export':await exportAudio();break;
case 'copyExtract':modal('원본 소리 그대로 추출','<p>출력 형식·비트레이트·보정·속도·반복 설정을 적용하지 않습니다. 원본 코덱에 맞는 형식으로 선택한 구간을 추출합니다. 정확한 경계가 필요하면 일반 변환을 이용하세요.</p><div class="actions">'+actionBtn('closeModal','돌아가기',null)+actionBtn('copyExtractConfirm','재인코딩 없이 추출','download','primary')+'</div>');break;
case 'copyExtractConfirm':closeModal();await exportAudio(true);break;
case 'download':if(result&&!result.stale)download(result.bytes,result.mime,result.name);break;
case 'playFinal':await chooseListen('final',true);break;
case 'backSettings':setTool('convert');$('panelTitle').scrollIntoView({behavior:'smooth',block:'nearest'});break;
case 'targetSize':{const target=num($('targetMb').value);const suggested=M.suggestBitrate(model(),target);targetBytes=Math.round(target*1000000);output.bitrate=suggested.bitrate;if(output.sampleRate>0&&output.sampleRate<32000&&output.bitrate>160)output.bitrate=160;output.vbr=false;invalidate();renderLayout();persistOutput();toast(suggested.possible?`${suggested.bitrate} kbps를 제안합니다. 실제 용량은 변환 후 확인하세요.`:'최저 비트레이트로도 목표를 넘을 수 있습니다. 구간을 줄여 주세요.',!suggested.possible);break}
case 'selectionGain':applyEdit('gain',{db:num(document.querySelector('[data-key="selectionGain"]').value)},'선택 구간 음량');break;
case 'resetEdits':if(activeSource)commit(M.create(activeSource),'편집 초기화');break;
case 'resetEffects':{const m=M.clone(model());m.effects={...M.effectsDefault(),limiter:false};commit(m,'모든 보정 끄기');break}
case 'addBackground':$('mixInput').click();break;
case 'removeBackground':{const m=M.clone(model());m.mix=null;commit(m,'배경음 제거');break}
case 'bookmark':applyEdit('bookmark',{time:editablePosition(),name:$('bookmarkName').value||'북마크'},'북마크 추가');break;
case 'splitFixed':applyEdit('splitFixed',{seconds:num($('splitSeconds').value,30)},'일정 길이로 분할');break;
case 'insertSilence':applyEdit('insertSilence',{time:model().selection.start,length:num($('insertSilenceSeconds').value,1)},'무음 삽입');break;
case 'repeatSelection':applyEdit('trim',{},'반복할 선택 구간 남기기');toast('선택한 구간을 남겼습니다. 반복 횟수를 설정하고 변환하세요.');break;
case 'detectSilence':await findSilence();break;
case 'applySilence':{const ranges=[...silenceRanges];applyEdit('removeRanges',{ranges},'탐지된 무음 제거');break}
case 'exportBookmarks':await exportSegments(true);break;
case 'exportClips':await exportSegments(false);break;
case 'savePreset':modal('내 보정 프리셋 저장','<label class="field"><span>이름</span><input id="presetName" maxlength="50" value="나의 수업 녹음"></label><p>소리 보정 값만 이 브라우저에 저장합니다. 구간과 원본 파일은 포함하지 않습니다.</p><div class="actions">'+actionBtn('confirmPreset','프리셋 저장','save','primary')+'</div>');break;
case 'confirmPreset':{const name=$('presetName').value.trim();if(!name){toast('프리셋 이름을 입력해 주세요.',true);break}const p=getPresets();p.push({id:'user_'+Date.now(),name,effects:model().effects});if(putPresets(p.slice(-50))){closeModal();renderPanel();toast('보정 프리셋을 저장했습니다.')}break}
case 'managePresets':modal('저장한 보정 프리셋',getPresets().length?getPresets().map((p,i)=>`<div class="batch-row"><input id="preset-edit-${i}" value="${esc(p.name)}" maxlength="50" aria-label="프리셋 이름"><button class="btn" data-preset-rename="${i}">이름 변경</button><button class="btn danger" data-preset-delete="${i}">삭제</button></div>`).join(''):'<p>저장한 프리셋이 없습니다.</p>');break;
case 'saveProject':saveProject();break;
case 'loadProject':$('projectInput').click();break;
case 'offline':await offline();break;
case 'clearCache':await offline(true);break;
case 'recordStart':await startRecording();break;
case 'recordPause':if(recorder?.state==='recording'){recordElapsed=Date.now()-recordStarted;recorder.pause()}else if(recorder?.state==='paused'){recordStarted=Date.now()-recordElapsed;recorder.resume()}renderAux();break;
case 'recordStop':stopRecording();break;
case 'recordCancel':stopRecording(true);break;
case 'batchAdd':$('batchInput').click();break;
case 'batchStart':await runBatch();break;
case 'batchClear':if(!batchRunning){batch=[];renderAux()}break;
case 'batchZip':downloadZip(batch.filter(b=>b.result).map(b=>({name:b.name,extension:b.result.extension,bytes:b.result.bytes})),`일괄변환_${localDate()}`);break;
case 'segmentZip':downloadZip(segmentResults.map(r=>({name:r.name,extension:r.extension,bytes:r.bytes})),`${outputName}_구간별`);break;
}}
document.addEventListener('click',async e=>{const el=e.target.closest('button,a');if(!el)return;try{if(el.dataset.action){e.preventDefault();await action(el.dataset.action)}else if(el.dataset.tool)setTool(el.dataset.tool);else if(el.dataset.format)applyFormat(el.dataset.format);else if(el.dataset.menu)chooseMenu(el.dataset.menu);else if(el.dataset.color){output.videoColor=el.dataset.color;invalidate();renderLayout();persistOutput()}else if(el.dataset.listen)await chooseListen(el.dataset.listen);else if(el.dataset.clipAction){const i=num(el.dataset.index),op=el.dataset.clipAction;if(op==='up'||op==='down')applyEdit('reorder',{from:i,to:i+(op==='up'?-1:1)},'구간 순서 변경');else applyEdit(op==='remove'?'removeClip':'duplicateClip',{index:i},op==='remove'?'구간 삭제':'구간 복제')}else if(el.hasAttribute('data-bookmark')){const b=model().bookmarks[num(el.dataset.bookmark)];const end=Math.min(M.baseDuration(model()),b.time+1);updateSelection(Math.min(b.time,end-.001),end);stopPlayback(false);seekToEdit(b.time);toast(`‘${b.name}’ 위치로 이동했어요. 재생하거나 이 구간 미리 듣기로 확인하세요.`)}else if(el.hasAttribute('data-remove-bookmark'))applyEdit('removeBookmark',{index:num(el.dataset.removeBookmark)},'북마크 삭제');else if(el.hasAttribute('data-batch-remove')){batch.splice(num(el.dataset.batchRemove),1);renderAux()}else if(el.hasAttribute('data-batch-up')){const i=num(el.dataset.batchUp);[batch[i],batch[i-1]]=[batch[i-1],batch[i]];renderAux()}else if(el.hasAttribute('data-batch-download')){const b=batch[num(el.dataset.batchDownload)];download(b.result.bytes,b.result.mime,M.safeFilename(b.name,b.result.extension))}else if(el.hasAttribute('data-segment-download')){const r=segmentResults[num(el.dataset.segmentDownload)];download(r.bytes,r.mime,r.name)}else if(el.hasAttribute('data-silence-listen')){const r=silenceRanges[num(el.dataset.silenceListen)];updateSelection(r.start,r.end);await preparePreview(true)}else if(el.hasAttribute('data-preset-rename')){const i=num(el.dataset.presetRename),p=getPresets(),name=$('preset-edit-'+i).value.trim();if(!name)throw new Error('이름을 입력해 주세요.');p[i].name=name;putPresets(p);renderPanel();toast('이름을 바꿨습니다.')}else if(el.hasAttribute('data-preset-delete')){const p=getPresets();p.splice(num(el.dataset.presetDelete),1);putPresets(p);action('managePresets');renderPanel()}}catch(error){toast(error.message||'설정을 적용하지 못했습니다.',true)}});
document.addEventListener('input',e=>{const el=e.target;if(el.type==='range'&&el.dataset.key){const o=el.closest('label')?.querySelector('output');if(o)o.textContent=el.value}if(el.id==='listenVolume'&&playerGain)playerGain.gain.value=listenerGain();if(el.id==='waveScroll'){scroll=num(el.value);drawWave()}});
document.addEventListener('change',async e=>{const el=e.target;try{if(el.dataset.key){const key=el.dataset.key,scope=el.dataset.scope||'model';if(scope==='special'){if(key==='preset')outputPreset(el.value);else if(key==='effectPreset')effectPreset(el.value);else if(key==='outputName'){outputName=el.value;if(result&&!result.stale){result.name=M.safeFilename(outputName,result.extension);renderResult();}}return}let value=el.type==='checkbox'?el.checked:el.type==='number'||el.type==='range'?num(el.value):el.value;if(scope==='output'){if(key==='format'){applyFormat(value);return}if(['bitrate','sampleRate','channels','bitDepth','quality','compression','oggQuality'].includes(key))value=num(value);output=M.validateOutput({...output,[key]:value});fitOutput();invalidate();renderLayout();persistOutput()}else{const m=M.clone(model());if(scope==='effects')m.effects[key]=value;else if(scope==='mix')m.mix[key]=value;else m[key]=value;commit(M.validateModel(m,sources),'설정 변경')}}else if(el.id==='selectionStart'||el.id==='selectionEnd')updateSelection(num($('selectionStart').value),num($('selectionEnd').value));else if(el.id==='seek'){const was=playing,target=num(el.value);stopPlayback(false);position=Math.max(0,Math.min(playerBuffer?.duration||0,target));updatePlaybackUI();drawWave();if(was)startPlayback()}else if(el.id==='matchVolume'){compareMatch=el.checked;if(playerGain)playerGain.gain.value=listenerGain()}else if(el.id==='listenSpeed'){const was=playing;if(was){stopPlayback(false);startPlayback()}}else if(el.id==='audioTrack'){const file=activeSource.file;await loadFile(file,'replace',num(el.value))}else if(el.hasAttribute('data-batch-format')){const b=batch[num(el.dataset.batchFormat)];b.output.format=el.value;fitOutput(b.output,false);b.result=null;b.message='대기 중';renderAux()}else if(el.hasAttribute('data-batch-preset')){const b=batch[num(el.dataset.batchPreset)];b.preset=el.value;b.output.bitrate=el.value==='speech'?96:el.value==='music'?320:192;b.output.oggQuality=el.value==='speech'?2:el.value==='music'?8:4;b.output.channels=el.value==='speech'?1:0;fitOutput(b.output,false);b.result=null;b.message='대기 중';renderAux()}else if(el.hasAttribute('data-batch-name'))batch[num(el.dataset.batchName)].name=el.value;else if(el.hasAttribute('data-bookmark-name')){const name=el.value.trim();if(!name){toast('북마크 이름을 입력해 주세요.',true);renderPanel();return}const i=num(el.dataset.bookmarkName),typing=document.activeElement===el;applyEdit('renameBookmark',{index:i,name},'북마크 이름 변경');if(typing)$('panelBody').querySelector(`[data-bookmark-name="${i}"]`)?.focus()}}catch(err){toast(err.message,true);if(model())renderLayout()}});
$('fileInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';await loadFile(f)});$('coverInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';await chooseCover(f)});$('appendInput').addEventListener('change',async e=>{const files=[...e.target.files];e.target.value='';for(const f of files)await loadFile(f,'append')});$('mixInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';await loadFile(f,'mix')});$('batchInput').addEventListener('change',e=>{addBatch([...e.target.files]);e.target.value=''});$('projectInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';await importProject(f)});
let dragStart=null,dragMoved=false;function waveTime(e){const r=$('waveCanvas').getBoundingClientRect(),d=M.baseDuration(model()),shown=d/zoom;return Math.max(0,Math.min(d,scroll*(d-shown)+(e.clientX-r.left)/r.width*shown))}
$('waveWrap').addEventListener('pointerdown',e=>{if(!model()||processing)return;dragStart=waveTime(e);dragMoved=false;$('waveWrap').setPointerCapture(e.pointerId)});$('waveWrap').addEventListener('pointermove',e=>{if(dragStart===null)return;const at=waveTime(e);if(Math.abs(at-dragStart)>.003){dragMoved=true;history.updateSelection(Math.min(at,dragStart),Math.max(at,dragStart));renderSelection();drawWave()}});$('waveWrap').addEventListener('pointerup',e=>{if(dragStart===null)return;if(!dragMoved){stopPlayback(false);if(!seekToEdit(waveTime(e)))toast('이 구간의 소리는 구간 선택 후 미리 듣기로 확인해 주세요.')}dragStart=null});$('waveWrap').addEventListener('pointercancel',()=>dragStart=null);
let dragDepth=0;document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault()});document.addEventListener('dragenter',e=>{if(e.dataTransfer.types.includes('Files')){dragDepth++;document.body.classList.add('dragging')}});document.addEventListener('dragleave',()=>{if(--dragDepth<=0)document.body.classList.remove('dragging')});document.addEventListener('drop',async e=>{e.preventDefault();dragDepth=0;document.body.classList.remove('dragging');if(processing)return;const files=[...e.dataTransfer.files];if(files.length===1&&/\.json$/i.test(files[0].name)){await importProject(files[0]);return}if(files.length>1||tool==='batch')addBatch(files);else if(files.length)await loadFile(files[0])});
document.addEventListener('keydown',e=>{if($('modal').open||processing||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable)return;if(!(e.target.closest('#workspace')||e.target.closest('.rail')||e.target===document.body))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();action(e.shiftKey?'redo':'undo')}else if(e.code==='Space'&&activeSource){e.preventDefault();action('play')}else if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&activeSource){e.preventDefault();action(e.key==='ArrowLeft'?'back':'forward')}else if(/^[1-8]$/.test(e.key)&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();setTool(Object.keys(toolsInfo)[Number(e.key)-1])}});
window.addEventListener('beforeunload',e=>{if(dirty||recorder){e.preventDefault();e.returnValue=''}});window.addEventListener('pagehide',()=>{releaseMic();engine.dispose();for(const url of downloadUrls)URL.revokeObjectURL(url)});new ResizeObserver(()=>{drawWave();drawMixWave();drawCoverPreview()}).observe($('workspace'));
function syncThemeButton(){const dark=document.documentElement.dataset.theme==='dark',b=document.querySelector('[data-action="theme"]');b.innerHTML=icon(dark?'sun':'moon');b.setAttribute('aria-pressed',String(dark));b.title=dark?'밝은 화면으로 바꾸기':'어두운 화면으로 바꾸기'}syncThemeButton();
if(location.protocol==='file:'){$('welcome').insertAdjacentHTML('beforebegin','<div class="hint warn">화면은 열렸지만 음원 처리는 HTTP 실행이 필요합니다. 이 폴더의 실행 안내.txt 또는 README.md를 참고해 주세요.</div>')}
// A copied or uploaded folder can lose the 32 MB engine file; say so before a teacher picks a file.
// Only a real "not found" answer counts: offline use (no network) must not show this warning.
else fetch('vendor/ffmpeg-core.wasm',{method:'HEAD',cache:'no-store'}).then(r=>{if(!r.ok)$('welcome').insertAdjacentHTML('beforebegin','<div class="hint warn" role="alert"><strong>변환 엔진 파일이 없습니다.</strong> vendor 폴더의 ffmpeg-core.wasm(약 32 MB)을 찾지 못해 파일을 열거나 변환할 수 없어요. 사이트 폴더 전체를 다시 복사하거나 올려 주세요.</div>')}).catch(()=>{});
restoreOutput();
try{document.fonts?.load('700 48px Pretendard')}catch{}
renderLayout();
})();
